import type { RedFlagScenario, RedFlagTag } from "./types.ts";
import { packSlots, retiredKeys } from "./red-flag-packs.ts";

// Red Flag Mayın Tarlası — 60 senaryo (6 tema × 10), TR/EN/ES.
// Yazım kuralları:
//  - İkinci tekil kişi ("Sevgilin…", "Arkadaşın…", "your partner…", "tu pareja…"): cinsiyetsiz ve kişisel.
//  - Tek bir "genel" havuz: bağlam (sevgili / arkadaş) senaryodan senaryoya doğal olarak değişir.
//  - Doğru cevap yoktur; her temada net sağlıklı, gri ve endişe verici örnekler karışık bulunur.
//  - İstismarı/şiddeti hafife alan veya mağduru yargılayan içerik yok; ton yargısız.
const s = (tag: RedFlagTag, n: number, tr: string, en: string, es: string): RedFlagScenario => ({ tag, n, tr, en, es });

const baseScenarios: RedFlagScenario[] = [
  // ── boundaries ──────────────────────────────────────────────────────
  s("boundaries", 1,
    "Sevgilin, eski sevgilisinin hediyesini hâlâ odasındaki rafta saklıyor.",
    "Your partner still keeps a gift from their ex on a shelf in their room.",
    "Tu pareja sigue guardando un regalo de su ex en una estantería de su habitación."),
  s("boundaries", 2,
    "Arkadaşlarınla plan yaptığında partnerin “Tabii git, iyi eğlenin” diyor ve gerçekten sorun etmiyor.",
    "When you make plans with friends, your partner says “Of course, have fun” and genuinely means it.",
    "Cuando quedas con tus amigos, tu pareja dice «claro, que lo paséis bien» y lo dice de verdad."),
  s("boundaries", 3,
    "Çok yorgun olduğunda arkadaşın “Bugün konuşamayacağım, yarın arayayım mı?” diyor.",
    "When your friend is wiped out, they say “I can't talk today, can I call you tomorrow?”",
    "Cuando tu amigo anda muy cansado, te dice «hoy no puedo hablar, ¿te llamo mañana?»."),
  s("boundaries", 4,
    "Yeni tanıştığın biri, ilk haftada sürekli “Neredesin, kiminlesin?” diye yazıyor.",
    "Someone you just met keeps texting “Where are you, who are you with?” all through the first week.",
    "Alguien a quien acabas de conocer te escribe sin parar «¿dónde estás, con quién?» durante la primera semana."),
  s("boundaries", 5,
    "Partnerin, izin almadan telefonunu “Sadece merak ettim” diyerek karıştırdı.",
    "Your partner went through your phone without asking, saying “I was just curious.”",
    "Tu pareja revisó tu móvil sin pedirte permiso, diciendo «solo tenía curiosidad»."),
  s("boundaries", 6,
    "Arkadaşın, sana ait özel bir şeyi herkesin içinde gülerek anlattı ve “Şaka yaptım” dedi.",
    "A friend laughingly told a group something private about you and said “I was only joking.”",
    "Un amigo contó entre risas algo privado tuyo delante de todos y dijo «era broma»."),
  s("boundaries", 7,
    "Hafta sonunu tek başına geçirmek istediğini söyleyince sevgilin “Tamam, kendine iyi bak” dedi.",
    "When you said you wanted a weekend to yourself, your partner said “Okay, take care of yourself.”",
    "Cuando dijiste que querías pasar el fin de semana a solas, tu pareja respondió «vale, cuídate»."),
  s("boundaries", 8,
    "Sevgilin, restoranda sormadan senin yerine sipariş verdi ve “Onu yeme” dedi.",
    "Your partner ordered for you at a restaurant without asking and said “Don't eat that.”",
    "Tu pareja pidió por ti en el restaurante sin preguntarte y te dijo «eso no lo comas»."),
  s("boundaries", 9,
    "Arkadaşın, haber vermeden evine misafir getirdi ve “Sorun olmaz, değil mi?” dedi.",
    "A friend brought guests to your home without warning and said “That's fine, right?”",
    "Un amigo llevó invitados a tu casa sin avisar y dijo «no pasa nada, ¿verdad?»."),
  s("boundaries", 10,
    "İlişkinizin ilk ayında partnerin tüm sosyal medya şifrelerini paylaşmayı önerdi.",
    "In the first month, your partner suggested you share all your social media passwords.",
    "En el primer mes, tu pareja propuso compartir todas vuestras contraseñas de redes sociales."),

  // ── trust ───────────────────────────────────────────────────────────
  s("trust", 1,
    "Arkadaşın, sürpriz doğum günü planını saklamak için sana küçük bir yalan söyledi.",
    "A friend told you a small lie to hide a surprise birthday plan.",
    "Un amigo te dijo una pequeña mentira para ocultar una fiesta sorpresa de cumpleaños."),
  s("trust", 2,
    "Nerede olduğunu sorduğun mesaja partnerin üç saat sonra “Telefonumun şarjı bitmişti” diye döndü.",
    "Your partner answered “Where are you?” three hours later with “My phone died.”",
    "Tu pareja respondió tres horas después a «¿dónde estás?» con «se me acabó la batería»."),
  s("trust", 3,
    "Sevgilin, eski sevgilisiyle haftada bir mesajlaşıyor ve bunu saklamadan söylüyor.",
    "Your partner texts their ex once a week and tells you about it openly.",
    "Tu pareja se escribe una vez por semana con su ex y te lo cuenta abiertamente."),
  s("trust", 4,
    "Arkadaşın, sana ait bir sırrı “Sadece en yakın arkadaşıma anlattım” diyerek başkasıyla paylaştı.",
    "A friend shared your secret with someone else, saying “I only told my closest friend.”",
    "Un amigo contó tu secreto a otra persona diciendo «solo se lo conté a mi mejor amigo»."),
  s("trust", 5,
    "Partnerin, uzun süredir sakladığı bir borcu bir tartışmanın ortasında ortaya çıkardı.",
    "Your partner revealed a long-hidden debt in the middle of an argument.",
    "Tu pareja reveló una deuda que ocultaba desde hacía tiempo en plena discusión."),
  s("trust", 6,
    "Sözünü sık sık unutan arkadaşın bu sefer “Unuttum, kusura bakma, telafi edeyim” diyerek özür diledi.",
    "A friend who often forgets promises apologized with “I forgot, I'm sorry, let me make it up to you.”",
    "Un amigo que suele olvidar sus promesas se disculpó con «se me olvidó, perdona, déjame compensarte»."),
  s("trust", 7,
    "Partnerin hesap ekstrelerini sana hiç göstermiyor ama ortak giderlerdeki payını her ay zamanında ödüyor.",
    "Your partner never shows you their bank statements but pays their share of joint costs on time every month.",
    "Tu pareja nunca te enseña sus extractos bancarios, pero paga a tiempo su parte de los gastos comunes cada mes."),
  s("trust", 8,
    "Arkadaşın, başkalarının yanında senin hakkında güzel konuşuyor ama yalnızken seni eleştiriyor.",
    "A friend speaks well of you in front of others but criticizes you in private.",
    "Un amigo habla bien de ti delante de otros, pero te critica en privado."),
  s("trust", 9,
    "Geç saatte kiminle olduğunu sorduğunda sevgilin bir an duraksayıp “Bir arkadaşım” diyor ve konuyu değiştiriyor.",
    "When you ask who they're with late at night, your partner pauses, says “A friend,” and changes the subject.",
    "Cuando le preguntas con quién está a altas horas, tu pareja duda un momento, dice «un amigo» y cambia de tema."),
  s("trust", 10,
    "Arkadaşın, ona yanlışlıkla gelen özel mesajını okumadan silip sana haber verdi.",
    "A friend deleted a private message of yours that reached them by mistake, without reading it, and let you know.",
    "Un amigo borró sin leer un mensaje privado tuyo que le llegó por error y te avisó."),

  // ── communication ───────────────────────────────────────────────────
  s("communication", 1,
    "Tartışma sırasında partnerin “Çok geriliyorum, yarım saat sakinleşip konuşalım mı?” diyor.",
    "During an argument, your partner says “I'm getting too worked up, can we cool off for half an hour and talk?”",
    "En plena discusión, tu pareja dice «me estoy alterando demasiado, ¿nos calmamos media hora y hablamos?»."),
  s("communication", 2,
    "Bir şeye kırıldığında arkadaşın günlerce konuşmayıp yalnızca “Ben iyiyim” diyor.",
    "When something hurts them, your friend goes quiet for days and only says “I'm fine.”",
    "Cuando algo le duele, tu amigo se queda callado días y solo dice «estoy bien»."),
  s("communication", 3,
    "Partnerin, taşınma gibi önemli bir kararı seni bilgilendirmeden verip sonra “Sana söyleyecektim” diyor.",
    "Your partner makes a big decision, like moving, without telling you, then says “I was going to tell you.”",
    "Tu pareja toma una decisión importante, como mudarse, sin contártelo y luego dice «iba a decírtelo»."),
  s("communication", 4,
    "Arkadaşın, her tartışmada cümleleri “Sen hep böylesin” diye başlatıyor.",
    "In every argument, your friend starts sentences with “You're always like this.”",
    "En cada discusión, tu amigo empieza las frases con «tú siempre eres así»."),
  s("communication", 5,
    "Seni üzecek bir haberi sevgilin hemen söylemek yerine sakin bir akşamı kollayıp anlatıyor.",
    "Your partner waits for a calm evening to tell you upsetting news instead of dropping it on you at once.",
    "Tu pareja espera a una tarde tranquila para contarte una mala noticia en lugar de soltártela sin más."),
  s("communication", 6,
    "Arkadaşın mesajlarına günlerce cevap vermiyor ama sosyal medyada aktif.",
    "Your friend doesn't answer your messages for days but is active on social media.",
    "Tu amigo tarda días en responder tus mensajes, pero está activo en redes sociales."),
  s("communication", 7,
    "Bir sorunu konuşmak istediğinde partnerin telefonu bırakıp sana tüm dikkatini veriyor.",
    "When you want to talk about a problem, your partner puts the phone down and gives you their full attention.",
    "Cuando quieres hablar de un problema, tu pareja deja el móvil y te presta toda su atención."),
  s("communication", 8,
    "Tartıştığınız bir konuyu iki hafta sonra aniden açan sevgilin “Hâlâ aklımdaydı” diyor.",
    "Two weeks after an argument, your partner suddenly brings it up again, saying “It's still on my mind.”",
    "Dos semanas después de una discusión, tu pareja vuelve a sacar el tema diciendo «me sigue rondando la cabeza»."),
  s("communication", 9,
    "Fikrini söylediğinde arkadaşın “Abartıyorsun” diyerek konuyu kapatıyor.",
    "When you share your view, your friend shuts it down with “You're overreacting.”",
    "Cuando das tu opinión, tu amigo cierra el tema con «estás exagerando»."),
  s("communication", 10,
    "Seninle aynı fikirde olmadığında bile partnerin görüşünü sakin ve saygılı biçimde anlatıyor.",
    "Even when they disagree with you, your partner explains their view calmly and respectfully.",
    "Aunque no esté de acuerdo contigo, tu pareja explica su punto de vista con calma y respeto."),

  // ── jealousy ────────────────────────────────────────────────────────
  s("jealousy", 1,
    "Arkadaşlarınla çekilmiş bir fotoğrafta bir kişiyi gören sevgilin “Bu kim?” diye merak ediyor.",
    "Your partner asks “Who's that?” about someone in a photo of you with friends.",
    "Tu pareja pregunta «¿quién es?» por alguien en una foto tuya con amigos."),
  s("jealousy", 2,
    "Başka biriyle yakınlaştığında arkadaşın “Beni artık sevmiyorsun” diyerek küsüyor.",
    "When you get closer to someone else, your friend sulks, saying “You don't like me anymore.”",
    "Cuando te acercas a otra persona, tu amigo se enfada diciendo «ya no me quieres»."),
  s("jealousy", 3,
    "Partnerin, iş arkadaşınla yemeğe katılmak istemediğini söylüyor ama sana “İyi eğlenin” diyor.",
    "Your partner says they'd rather not join your dinner with a coworker, but tells you “Have a good time.”",
    "Tu pareja dice que prefiere no ir a tu cena con un compañero de trabajo, pero te dice «pasadlo bien»."),
  s("jealousy", 4,
    "Sevgilin, sosyal medyada beğendiğin gönderileri tek tek kontrol edip soruyor.",
    "Your partner checks the posts you like on social media one by one and asks about them.",
    "Tu pareja revisa una por una las publicaciones que te gustan en redes y te pregunta por cada una."),
  s("jealousy", 5,
    "Partnerin, eski sevgilini sorunca “Merak ettim ama konuşmak zorunda değiliz” diyor.",
    "Your partner asks about your ex and adds “I was curious, but we don't have to talk about it.”",
    "Tu pareja pregunta por tu ex y añade «tenía curiosidad, pero no hace falta que hablemos de ello»."),
  s("jealousy", 6,
    "Terfi aldığında arkadaşın sevinmek yerine “Demek bu kadar şanslısın” diyerek soğuk karşılıyor.",
    "When you get a promotion, your friend greets it coldly with “So you're just that lucky.”",
    "Cuando te ascienden, tu amigo lo recibe con frialdad: «así que tienes tanta suerte»."),
  s("jealousy", 7,
    "Yokluğunda arkadaşlarınla neler konuştuğunu öğrenmek için sevgilin sana soru yağdırıyor.",
    "Your partner bombards you with questions about what you talked about with friends while they weren't there.",
    "Tu pareja te acribilla a preguntas sobre lo que hablaste con tus amigos en su ausencia."),
  s("jealousy", 8,
    "Onsuz gittiğin bir etkinliği partnerin hevesle dinleyip “Çok sevindim, anlat bakalım” diyor.",
    "Your partner eagerly listens about an event you went to without them and says “I'm so glad, tell me everything.”",
    "Tu pareja escucha con ganas cómo te fue en un evento al que no pudo acompañarte y dice «me alegro mucho, cuéntamelo todo»."),
  s("jealousy", 9,
    "Başka bir arkadaşınla vakit geçirdiğinde arkadaşın sana “Beni dışladınız” diye mesaj atıyor.",
    "When you spend time with another friend, your friend messages you “You left me out.”",
    "Cuando pasas tiempo con otro amigo, tu amigo te escribe «me habéis dejado fuera»."),
  s("jealousy", 10,
    "Sevgilin, seni başkalarıyla kıyaslayıp “Başkaları çok daha ilgili” diyor.",
    "Your partner compares you to others, saying “Other people are so much more attentive.”",
    "Tu pareja te compara con otras personas diciendo «otras personas son mucho más atentas»."),

  // ── money_lifestyle ─────────────────────────────────────────────────
  s("money_lifestyle", 1,
    "Partnerin, ortak bir hedef için aylık birikim yapmayı öneriyor ve kendi payını önceden ayırıyor.",
    "Your partner suggests saving monthly for a shared goal and sets aside their own share in advance.",
    "Tu pareja propone ahorrar cada mes para una meta común y aparta su parte por adelantado."),
  s("money_lifestyle", 2,
    "Arkadaşın, her yemekte hesabı “Sonra denkleştiririz” diyerek sana bırakıyor.",
    "At every meal, your friend leaves you the bill, saying “We'll even it out later.”",
    "En cada comida, tu amigo te deja la cuenta diciendo «ya lo igualamos luego»."),
  s("money_lifestyle", 3,
    "Maaşını ne yaptığını sorduğunda sevgilin “Bu benim işim” diyerek konuyu kapatıyor.",
    "When you ask what they do with their salary, your partner shuts it down with “That's my business.”",
    "Cuando le preguntas qué hace con su sueldo, tu pareja cierra el tema con «eso es asunto mío»."),
  s("money_lifestyle", 4,
    "Doğum gününde partnerin bütçenizi aşan pahalı bir hediye alıp “Hak ettin” diyor.",
    "On your birthday, your partner buys an expensive gift that stretches your budget, saying “You deserve it.”",
    "En tu cumpleaños, tu pareja compra un regalo caro que se pasa de vuestro presupuesto diciendo «te lo mereces»."),
  s("money_lifestyle", 5,
    "Arkadaşın, borç aldığı parayı geri verirken küçük bir hediye ekleyip teşekkür ediyor.",
    "A friend returns money they borrowed and adds a small gift as thanks.",
    "Un amigo te devuelve el dinero que le prestaste y añade un pequeño regalo de agradecimiento."),
  s("money_lifestyle", 6,
    "Sevgilin, tatil planlarını tek başına yapıp sana yalnızca tarihleri bildiriyor.",
    "Your partner plans the whole vacation alone and only tells you the dates.",
    "Tu pareja organiza las vacaciones sin ti y solo te comunica las fechas."),
  s("money_lifestyle", 7,
    "Partnerin, ev işlerini bir tabloda tutuyor ve yarı yarıya paylaşmanız için sizi uyarıyor.",
    "Your partner keeps a chart of household chores and nudges you to split them fifty-fifty.",
    "Tu pareja lleva una tabla de las tareas del hogar y os insta a repartirlas al cincuenta por ciento."),
  s("money_lifestyle", 8,
    "Arkadaşın, planları son dakikada tekrar tekrar iptal edip “Enerjim yok” diyor.",
    "Your friend cancels plans at the last minute again and again, saying “I have no energy.”",
    "Tu amigo cancela los planes a última hora una y otra vez diciendo «no tengo energía»."),
  s("money_lifestyle", 9,
    "Sevgilin, kariyer fırsatın için başka şehre taşınmanı destekleyip uzak mesafeyi denemeyi öneriyor.",
    "Your partner supports you moving cities for a career opportunity and suggests trying long distance.",
    "Tu pareja te apoya para mudarte de ciudad por una oportunidad profesional y propone probar la distancia."),
  s("money_lifestyle", 10,
    "Partnerin, ortak hesaptan senin haberin olmadan büyük bir harcama yaptı.",
    "Your partner made a large purchase from your joint account without telling you.",
    "Tu pareja hizo una compra grande desde la cuenta común sin decírtelo."),

  // ── respect ─────────────────────────────────────────────────────────
  s("respect", 1,
    "Arkadaşın, başkalarının yanında seni yarıda kesip fikrini “Saçmalama” diye geçiştiriyor.",
    "In front of others, your friend cuts you off and brushes off your opinion with “Don't be silly.”",
    "Delante de otros, tu amigo te interrumpe y despacha tu opinión con «no digas tonterías»."),
  s("respect", 2,
    "Yanlış yaptığında partnerin hemen “Haklısın, özür dilerim” diyor.",
    "When your partner gets something wrong, they say right away “You're right, I'm sorry.”",
    "Cuando tu pareja se equivoca, dice enseguida «tienes razón, perdona»."),
  s("respect", 3,
    "Sevgilin, sana sürekli “Kıyafetini değiştirsen daha iyi olur” gibi yorumlar yapıyor.",
    "Your partner keeps commenting “You'd look better if you changed your outfit.”",
    "Tu pareja te hace comentarios constantes como «estarías mejor si te cambiaras de ropa»."),
  s("respect", 4,
    "Arkadaşın, seninle konuşurken sürekli telefonuna bakıyor ama “Seni dinliyorum” diyor.",
    "While you talk, your friend keeps checking their phone but says “I'm listening.”",
    "Mientras le hablas, tu amigo no deja de mirar el móvil, pero dice «te escucho»."),
  s("respect", 5,
    "Partnerin, arkadaşlarına senin hakkında mizahi ama kırıcı hikâyeler anlatıyor.",
    "Your partner tells their friends funny but hurtful stories about you.",
    "Tu pareja cuenta a sus amigos historias graciosas pero hirientes sobre ti."),
  s("respect", 6,
    "Bir tartışmada sevgilin sesini yükseltmeden “Bunu daha sonra konuşalım” diyerek odadan çıkıyor.",
    "In an argument, your partner leaves the room without raising their voice, saying “Let's talk about this later.”",
    "En una discusión, tu pareja sale de la habitación sin levantar la voz diciendo «lo hablamos más tarde»."),
  s("respect", 7,
    "Başarını kutlarken arkadaşın bir de “Ama şu kısmı eksikti” diye ekliyor.",
    "While congratulating you on an achievement, your friend adds “But this part was missing.”",
    "Al felicitarte por un logro, tu amigo añade «pero faltaba esta parte»."),
  s("respect", 8,
    "Sen “Hayır” dediğinde partnerin üstelemiyor ama bir süre mesafeli davranıyor.",
    "When you say “No,” your partner doesn't push, but acts distant for a while.",
    "Cuando dices «no», tu pareja no insiste, pero se muestra distante un tiempo."),
  s("respect", 9,
    "Seninle tartışırken arkadaşın geçmişteki hatalarını tek tek sayıp döküyor.",
    "When arguing with you, your friend lists your past mistakes one by one.",
    "Cuando discute contigo, tu amigo enumera tus errores del pasado uno por uno."),
  s("respect", 10,
    "Başkalarının yanında sevgilin gülerek sana “Zaten sen bir şey bilmezsin” diyor.",
    "In front of others, your partner laughs and says “You don't know anything anyway.”",
    "Delante de otros, tu pareja se ríe y dice «si tú no sabes nada»."),

  // ── Arkadaşlık setlerini tamamlayan yeni senaryolar (11+) ───────────
  s("boundaries", 11,
    "Mesajına hemen cevap veremediğinde arkadaşın üstelemiyor, “Müsait olunca yaz” diyor.",
    "When you can't reply right away, your friend doesn't push and says “Write back when you're free.”",
    "Cuando no puedes responder enseguida, tu amigo no insiste y te dice «escríbeme cuando puedas»."),
  s("boundaries", 12,
    "Söylediği bir şaka seni rahatsız ettiğinde arkadaşın hemen özür diliyor ve bir daha tekrarlamıyor.",
    "When a joke of theirs makes you uncomfortable, your friend apologizes right away and doesn't repeat it.",
    "Cuando una broma suya te incomoda, tu amigo se disculpa enseguida y no la repite."),
  s("jealousy", 11,
    "Yeni bir arkadaş grubuna katıldığında arkadaşın “Çok sevindim, bir gün tanıştır bizi” diyor.",
    "When you join a new group of friends, your friend says “I'm so happy for you, introduce us sometime.”",
    "Cuando te unes a un nuevo grupo de amigos, tu amigo dice «me alegro mucho, preséntanos algún día»."),
  s("jealousy", 12,
    "Başka bir arkadaşınla tatile çıkacağını söylediğinde arkadaşın “Tamam, iyi eğlenin” deyip birkaç gün mesaj atmıyor.",
    "When you tell your friend you're going on holiday with someone else, they say “Okay, have fun” and don't text for a few days.",
    "Cuando dices que te vas de vacaciones con otro amigo, tu amigo responde «vale, pasadlo bien» y pasa unos días sin escribir."),
  s("money_lifestyle", 11,
    "Ortak yaptığınız bir harcamada arkadaşın hesabı hemen çıkarıp “Payım şu kadar” diye net bir mesaj atıyor.",
    "After a shared expense, your friend works out the split right away and texts you a clear “My share is this much.”",
    "Tras un gasto compartido, tu amigo calcula enseguida la cuenta y te manda un mensaje claro: «mi parte es esta»."),
];

/** Sete yerleştirme (pack/pos) ve pasif işaretleri seed'e uygulanmış nihai liste */
export const redFlagScenarios: RedFlagScenario[] = baseScenarios.map((sc) => {
  const key = `${sc.tag}:${sc.n}`;
  const slot = packSlots[key];
  return { ...sc, ...(slot ? { pack: slot.pack, pos: slot.pos, tone: slot.tone } : {}), ...(retiredKeys.includes(key) ? { inactive: true } : {}) };
});
