// Red Flag Mayın Tarlası — set (deste) dağılımı. Üreten: tek seferlik atama; kartlar sabit sırayla (pos) sunulur.
// Her set 9 kart: 6 temanın tamamını kapsar, ton (sağlıklı/gri/endişe verici) dengelidir. Yalnızca aynı set içindeki
// tolerans yüzdeleri karşılaştırılabilir.
//  - friend-10x  : "Arkadaşlık"   - romantic-10x : "Sevgili"
//  - 101-103 webde oynanır; 104-106 ileride (mobilde açılacak) doldurulur.
//  - tone: H = sağlıklı, G = gri, C = endişe verici (yalnızca yazım/inceleme notu; DB'ye yazılmaz).
export interface PackSlot { pack: string; pos: number; tone: "H" | "G" | "C" }

export const packSlots: Record<string, PackSlot> = {
  "money_lifestyle:5": { pack: "friend-101", pos: 1, tone: "H" },
  "communication:9": { pack: "friend-101", pos: 2, tone: "C" },
  "trust:1": { pack: "friend-101", pos: 3, tone: "H" },
  "jealousy:12": { pack: "friend-101", pos: 4, tone: "G" },
  "boundaries:3": { pack: "friend-101", pos: 5, tone: "H" },
  "respect:7": { pack: "friend-101", pos: 6, tone: "G" },
  "trust:8": { pack: "friend-101", pos: 7, tone: "C" },
  "respect:4": { pack: "friend-101", pos: 8, tone: "G" },
  "boundaries:6": { pack: "friend-101", pos: 9, tone: "C" },
  "boundaries:11": { pack: "friend-102", pos: 1, tone: "H" },
  "trust:4": { pack: "friend-102", pos: 2, tone: "C" },
  "respect:1": { pack: "friend-102", pos: 3, tone: "C" },
  "trust:6": { pack: "friend-102", pos: 4, tone: "G" },
  "money_lifestyle:11": { pack: "friend-102", pos: 5, tone: "H" },
  "jealousy:11": { pack: "friend-102", pos: 6, tone: "H" },
  "money_lifestyle:2": { pack: "friend-102", pos: 7, tone: "G" },
  "communication:6": { pack: "friend-102", pos: 8, tone: "G" },
  "jealousy:6": { pack: "friend-102", pos: 9, tone: "C" },
  "boundaries:12": { pack: "friend-103", pos: 1, tone: "H" },
  "respect:9": { pack: "friend-103", pos: 2, tone: "C" },
  "communication:2": { pack: "friend-103", pos: 3, tone: "C" },
  "boundaries:9": { pack: "friend-103", pos: 4, tone: "G" },
  "jealousy:9": { pack: "friend-103", pos: 5, tone: "G" },
  "communication:4": { pack: "friend-103", pos: 6, tone: "C" },
  "trust:10": { pack: "friend-103", pos: 7, tone: "H" },
  "money_lifestyle:8": { pack: "friend-103", pos: 8, tone: "G" },
  "jealousy:2": { pack: "friend-103", pos: 9, tone: "C" },
  "communication:1": { pack: "romantic-101", pos: 1, tone: "H" },
  "trust:7": { pack: "romantic-101", pos: 2, tone: "G" },
  "jealousy:1": { pack: "romantic-101", pos: 3, tone: "G" },
  "boundaries:5": { pack: "romantic-101", pos: 4, tone: "C" },
  "trust:5": { pack: "romantic-101", pos: 5, tone: "C" },
  "respect:2": { pack: "romantic-101", pos: 6, tone: "H" },
  "jealousy:5": { pack: "romantic-101", pos: 7, tone: "H" },
  "boundaries:10": { pack: "romantic-101", pos: 8, tone: "C" },
  "money_lifestyle:6": { pack: "romantic-101", pos: 9, tone: "C" },
  "jealousy:8": { pack: "romantic-102", pos: 1, tone: "H" },
  "communication:3": { pack: "romantic-102", pos: 2, tone: "C" },
  "respect:8": { pack: "romantic-102", pos: 3, tone: "G" },
  "money_lifestyle:10": { pack: "romantic-102", pos: 4, tone: "C" },
  "communication:8": { pack: "romantic-102", pos: 5, tone: "G" },
  "respect:3": { pack: "romantic-102", pos: 6, tone: "C" },
  "trust:2": { pack: "romantic-102", pos: 7, tone: "G" },
  "boundaries:7": { pack: "romantic-102", pos: 8, tone: "H" },
  "jealousy:7": { pack: "romantic-102", pos: 9, tone: "C" },
  "money_lifestyle:9": { pack: "romantic-103", pos: 1, tone: "H" },
  "boundaries:1": { pack: "romantic-103", pos: 2, tone: "G" },
  "jealousy:4": { pack: "romantic-103", pos: 3, tone: "C" },
  "boundaries:2": { pack: "romantic-103", pos: 4, tone: "H" },
  "respect:5": { pack: "romantic-103", pos: 5, tone: "C" },
  "communication:5": { pack: "romantic-103", pos: 6, tone: "H" },
  "trust:3": { pack: "romantic-103", pos: 7, tone: "G" },
  "money_lifestyle:4": { pack: "romantic-103", pos: 8, tone: "G" },
  "trust:9": { pack: "romantic-103", pos: 9, tone: "C" },
};

/** Hiçbir sette yer almayan, pasife alınmış senaryolar (silinmez; geçmiş oturumlar için saklanır). */
export const retiredKeys: string[] = [
  "boundaries:4",
  "boundaries:8",
  "communication:7",
  "communication:10",
  "jealousy:3",
  "jealousy:10",
  "money_lifestyle:3",
  "money_lifestyle:7",
  "respect:6",
  "respect:10",
  "money_lifestyle:1",
];
