export type QuestionSeed = {
  mode: "secret_choice";
  category: string;
  question_text: string;
  locale: string;
  is_active: boolean;
};

export const questions: QuestionSeed[] = [
  // communication (1–10)
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Her gün mesajlaşmak senin için önemli mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Günaydın mesajı almak hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Geç cevap verilmesi seni rahatsız eder mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Telefonda konuşmak yazışmadan daha iyi midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Gün içinde haberleşmek önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Partnerin yoğun olduğunda az yazması seni üzer mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Hislerini açıkça konuşmak senin için kolay mı?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Bir sorun olduğunda hemen konuşmak ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "Küçük detayları hatırlamak senin için önemli mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "communication",
    question_text: "İyi geceler mesajı almak hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },

  // first_date (11–20)
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada el ele tutuşmak doğal mı?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada uzun saatler geçirmek hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada fotoğraf çekmek ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada ikinci buluşmayı konuşmak doğru mu?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada eski ilişkilerden bahsetmek sorun olur mu?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada hesabı paylaşmak normal midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada çok soru sormak hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada sessizlik seni rahatsız eder mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada spontane plan değişikliği hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "first_date",
    question_text: "İlk buluşmada telefonla fazla ilgilenilmesi seni rahatsız eder mi?",
    locale: "tr",
    is_active: true,
  },

  // social_life (21–30)
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Partnerin sık arkadaşlarıyla çıkması normal midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Karşı cins yakın arkadaş olabilir mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Sosyal medyada ilişki paylaşmak ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Partnerin yalnız tatile gitmesi normal midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Kalabalık arkadaş ortamları hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Partnerinin arkadaşlarıyla yakın olmak ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Sosyal medyada çok aktif olmak seni rahatsız eder mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Ortak arkadaş çevresi ilişki için önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Partnerinin planlarını önceden bilmek ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "social_life",
    question_text: "Her hafta dışarı çıkmak sana iyi gelir mi?",
    locale: "tr",
    is_active: true,
  },

  // lifestyle (31–40)
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Hafta sonunu evde geçirmek hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Spontane planları sever misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Erken kalkmayı sever misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Gelecekte yurt dışında yaşamak ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Evde birlikte yemek yapmak hoşuna gider mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Planlı yaşamak senin için önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Tatilde dinlenmek gezmekten daha mı keyiflidir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Ev düzeni senin için çok önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Yeni yerler denemeyi sever misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "lifestyle",
    question_text: "Yoğun bir günün sonunda yalnız kalmak ister misin?",
    locale: "tr",
    is_active: true,
  },

  // values (41–50)
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Bir ilişkide özel alan önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Aile ilişkileri senin için çok önemli midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Kariyer ilişkiden önce gelebilir mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Duygusal destek ilişkide en önemli şeylerden biri midir?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Kıskançlık bazen sevgi göstergesi olabilir mi?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Para yönetimi ilişkide açıkça konuşulmalı mı?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Özür dilemek senin için kolay mı?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Partnerinle her şeyi paylaşmak ister misin?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Güven zamanla mı oluşur?",
    locale: "tr",
    is_active: true,
  },
  {
    mode: "secret_choice",
    category: "values",
    question_text: "Küçük sürprizler ilişkiyi canlı tutar mı?",
    locale: "tr",
    is_active: true,
  },
];
