import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Cesur Sorular — "dating" + "partner", premium, 18+. App Store: açık cinsel içerik YOK;
// cesur/romantik, dürüstlük, kırılganlık ve sınırlar çerçevesi.
export const bold: SeedCategory = {
  slug: "bold",
  names: { tr: "Cesur Sorular", en: "Bold Questions", es: "Preguntas atrevidas" },
  relationshipTypes: ["dating", "partner"],
  isPremium: true,
  sortOrder: 11,
  questions: [
    sc("small_secret",
      "Partnerine hiç söylemediğin küçük bir sırrın var mı?",
      "Is there a small secret you've never told your partner?",
      "¿Hay un pequeño secreto que nunca le has contado a tu pareja?"),
    sc("partner_exes",
      "Partnerinin eski sevgilileriyle iletişimde olması seni rahatsız eder mi?",
      "Would it bother you if your partner stayed in touch with their exes?",
      "¿Te molestaría que tu pareja siguiera en contacto con sus ex?"),
    sc("saying_jealousy",
      "Kıskançlık hissettiğinde bunu açıkça söyler misin?",
      "When you feel jealous, do you say so openly?",
      "Cuando sientes celos, ¿lo dices abiertamente?"),
    sc("phone_curiosity",
      "Partnerinin telefonuna izinsiz bakmayı hiç düşündün mü?",
      "Have you ever thought about looking at your partner's phone without permission?",
      "¿Alguna vez has pensado en mirar el móvil de tu pareja sin permiso?"),
    sc("white_lie_relationship",
      "İlişkinde bir kez bile “masum bir yalan” söyledin mi?",
      "Have you ever told a “white lie” in your relationship?",
      "¿Alguna vez has dicho una «mentira piadosa» en tu relación?"),
    sc("wild_together",
      "Partnerinle birlikte çılgınca bir şey (ani yolculuk, dövme vb.) yapmaya var mısın?",
      "Would you do something wild together (a spontaneous trip, a tattoo, etc.)?",
      "¿Te apuntarías a hacer algo alocado juntos (un viaje improvisado, un tatuaje, etc.)?"),
    sc("first_to_say_love",
      "“Seni seviyorum” demek için ilk adımı atmak senin için kolay mı?",
      "Is it easy for you to be the first to say “I love you”?",
      "¿Te resulta fácil ser el primero en decir «te quiero»?"),
    sc("still_attractive",
      "Partnerinin seni ilk günkü kadar çekici bulduğundan emin misin?",
      "Are you sure your partner finds you as attractive as on day one?",
      "¿Estás seguro de que tu pareja te sigue encontrando tan atractivo como el primer día?"),
    sc("secret_sharing",
      "Hayatında kimsenin bilmediği bir şeyi partnerine anlatmayı düşünür müsün?",
      "Would you consider telling your partner something nobody else knows about you?",
      "¿Te plantearías contarle a tu pareja algo que nadie más sabe de ti?"),
    sc("first_meeting_memory",
      "Partnerinle ilk karşılaşmanızı hâlâ ayrıntılı hatırlıyor musun?",
      "Do you still remember the details of the day you first met your partner?",
      "¿Todavía recuerdas con detalle el día en que conociste a tu pareja?"),

    pr("jealousy_reaction",
      ["Partnerin bir arkadaşıyla çok samimi görünüyor. Ne yaparsın?",
        ["Hiç sorun etmem, güvenirim", "Bir süre izler, içten içe rahatsız olurum", "Sonra sakince konuşup sorarım", "Hemen aralarına girerim"]],
      ["Your partner seems very close with a friend. What do you do?",
        ["No issue at all, I trust them", "Watch for a while, uneasy inside", "Calmly ask about it later", "Step in between them right away"]],
      ["Tu pareja parece muy cercana con un amigo. ¿Qué haces?",
        ["No me importa, confío", "Observo un rato, algo incómodo por dentro", "Más tarde le pregunto con calma", "Me meto enseguida entre ellos"]]),
    pr("confessing_mistake",
      ["Partnerine bir hata yaptığını itiraf etmen gerekiyor. Nasıl yaparsın?",
        ["Hemen, açık açık söylerim", "Uygun bir an kollayıp söylerim", "Önce kendimi savunacak gerekçeler hazırlarım", "Mümkünse hiç söylemem"]],
      ["You have to admit a mistake to your partner. How do you do it?",
        ["Right away, openly", "Wait for the right moment", "Prepare justifications first", "Avoid saying it if I can"]],
      ["Tienes que confesarle un error a tu pareja. ¿Cómo lo haces?",
        ["Enseguida y abiertamente", "Espero el momento oportuno", "Primero preparo mis justificaciones", "Evito decirlo si puedo"]]),
    pr("dare_choice",
      ["Partnerin senden bir “cesaret” görevi istiyor. Hangisini seçersin?",
        ["Herkesin önünde ona şarkı söylemek", "Ona bir aşk mektubu yazmak", "Sürpriz bir yolculuk planlamak", "Hiçbirini yapmam, “doğruluk” seçerim"]],
      ["Your partner dares you. Which do you pick?",
        ["Sing to them in front of everyone", "Write them a love letter", "Plan a surprise trip", "None, I'd choose “truth”"]],
      ["Tu pareja te propone un reto. ¿Cuál eliges?",
        ["Cantarle delante de todos", "Escribirle una carta de amor", "Planear un viaje sorpresa", "Ninguno, elegiría «verdad»"]]),
    pr("hard_truth",
      ["Partnerin “bana dürüstçe söyle, beni nasıl görüyorsun?” diye sordu. Ne dersin?",
        ["Her şeyi açık ve dürüst söylerim", "Önce iyi yanlarını, sonra kusurlarını söylerim", "Sadece olumlu şeyleri söylerim", "Şakayla geçiştiririm"]],
      ["Your partner asks, “be honest, how do you see me?” What do you say?",
        ["Say everything openly and honestly", "Mention the good first, then the flaws", "Say only positive things", "Brush it off with a joke"]],
      ["Tu pareja te pregunta: «sé sincero, ¿cómo me ves?». ¿Qué le dices?",
        ["Se lo digo todo con sinceridad", "Primero lo bueno y luego los defectos", "Solo digo cosas positivas", "Lo paso con una broma"]]),
    pr("midnight_adventure",
      ["Partnerinle bir gece yarısı maceraya atılma fırsatı doğdu. Ne yaparsın?",
        ["Hemen çıkarım", "Biraz nazlanır, sonra kabul ederim", "Önce planın güvenli olup olmadığını sorarım", "Sabaha bırakmayı teklif ederim"]],
      ["A midnight adventure with your partner pops up. What do you do?",
        ["Head out right away", "Hesitate a bit, then agree", "First ask if the plan is safe", "Suggest waiting until morning"]],
      ["Surge una aventura de medianoche con tu pareja. ¿Qué haces?",
        ["Salgo enseguida", "Me hago un poco de rogar y acepto", "Primero pregunto si el plan es seguro", "Propongo dejarlo para la mañana"]]),
    pr("surprise_reaction",
      ["Partnerin sana beklenmedik bir yerde romantik bir sürpriz yaptı. Ne yaparsın?",
        ["Çok duygulanıp sarılırım", "Gülüp ben de bir sürpriz hazırlamaya karar veririm", "Utanırım ama içten içe çok mutlu olurum", "Hemen herkese anlatırım"]],
      ["Your partner pulls off a romantic surprise in an unexpected place. What do you do?",
        ["Get emotional and hug them", "Laugh and plan a surprise of my own", "Feel shy but secretly very happy", "Tell everyone right away"]],
      ["Tu pareja te da una sorpresa romántica en un lugar inesperado. ¿Qué haces?",
        ["Me emociono y la abrazo", "Me río y decido preparar yo otra sorpresa", "Me da vergüenza pero estoy muy feliz por dentro", "Se lo cuento a todos enseguida"]]),
    pr("unknown_info",
      ["Partnerinin bir arkadaşı onun hakkında bilmediğin bir şey söyledi. Ne yaparsın?",
        ["Merak edip hemen sorarım", "Partnerime sonra sorarım", "Önemsemiyormuş gibi yapıp not ederim", "Rahatsız olur, konuyu uzatırım"]],
      ["A friend of your partner mentions something about them that you didn't know. What do you do?",
        ["Get curious and ask right away", "Ask my partner about it later", "Act unbothered but make a note", "Feel uneasy and press the topic"]],
      ["Un amigo de tu pareja menciona algo de ella que no sabías. ¿Qué haces?",
        ["Me da curiosidad y pregunto enseguida", "Se lo pregunto a mi pareja más tarde", "Hago como que no me importa pero lo apunto", "Me incomodo y sigo insistiendo en el tema"]]),
    pr("hurtful_words",
      ["Bir tartışmada partnerinin söylediği bir söz seni çok kırdı. Ne yaparsın?",
        ["O anda net şekilde söylerim", "Sakinleşince konuşurum", "Susar, mesafe koyarım", "Karşılık olarak ben de kırıcı bir şey söylerim"]],
      ["In an argument, something your partner says really hurts you. What do you do?",
        ["Tell them clearly in the moment", "Talk about it once I've calmed down", "Go silent and keep my distance", "Say something hurtful back"]],
      ["En una discusión, algo que dice tu pareja te duele mucho. ¿Qué haces?",
        ["Se lo digo claramente en ese momento", "Lo hablo cuando me haya calmado", "Me callo y pongo distancia", "Respondo diciendo algo hiriente"]]),
    pr("flaw_feedback",
      ["Partnerin senin bir eksikliğini nazikçe söyledi. Tepkin ne olur?",
        ["Teşekkür edip üzerinde çalışırım", "Savunmaya geçerim", "Önce üzülür, sonra düşünürüm", "Ona da bir eksikliğini söylerim"]],
      ["Your partner gently points out a flaw of yours. How do you react?",
        ["Thank them and work on it", "Get defensive", "Feel hurt first, then reflect", "Point out one of theirs in return"]],
      ["Tu pareja te señala con delicadeza un defecto tuyo. ¿Cómo reaccionas?",
        ["Le doy las gracias y trabajo en ello", "Me pongo a la defensiva", "Primero me duele y luego lo reflexiono", "Le señalo yo uno suyo"]]),
    pr("shared_secret",
      ["Partnerinle yalnızca ikinizin bildiği küçük bir “sır” (iç şaka, gizli bir plan) kurmak sana nasıl gelir?",
        ["Çok keyifli, bunu severim", "Eğlenceli ama abartmam", "Bunun pek önemi yok", "Sırların bağa zarar verebileceğini düşünürüm"]],
      ["How do you feel about having a small “secret” (inside joke, hidden plan) that only you two know?",
        ["Lovely, I enjoy that", "Fun, but I wouldn't overdo it", "Doesn't matter much", "I think secrets can harm the bond"]],
      ["¿Qué te parece tener un pequeño «secreto» (una broma interna, un plan oculto) que solo conocéis vosotros dos?",
        ["Me encanta", "Es divertido, pero sin pasarse", "No tiene mucha importancia", "Creo que los secretos dañan el vínculo"]]),

    ol("deal_breakers_bold",
      ["Bir ilişkide asla kabul edemeyeceğin şeyleri, en kabul edilemezden başlayarak sırala:", ["Aldatmak", "Sürekli yalan söylemek", "Kontrolcülük", "Saygısızlık"]],
      ["Rank what you could never accept in a relationship, starting with the least acceptable:", ["Cheating", "Constant lying", "Being controlling", "Disrespect"]],
      ["Ordena lo que jamás aceptarías en una relación, empezando por lo menos aceptable:", ["Engañar", "Mentir constantemente", "Ser controlador", "La falta de respeto"]]),
    ol("attraction_factors",
      ["Çekiciliği en çok belirleyen şeyleri sırala:", ["Zekâ ve mizah", "Özgüven", "Fiziksel görünüm", "Tutku ve enerji"]],
      ["Rank what most defines attraction:", ["Intelligence and humor", "Confidence", "Physical appearance", "Passion and energy"]],
      ["Ordena lo que más define la atracción:", ["Inteligencia y humor", "Seguridad en uno mismo", "Aspecto físico", "Pasión y energía"]]),
    ol("love_risks",
      ["Bir ilişkide göze alabileceğin riskleri, en kolay göze alacağından başlayarak sırala:", ["Uzak mesafe", "Şehir değiştirmek", "Ailenin karşı çıkması", "Yaş farkı"]],
      ["Rank the risks you'd take in a relationship, starting with the one you'd take most readily:", ["Long distance", "Moving cities", "Family disapproval", "An age gap"]],
      ["Ordena los riesgos que asumirías en una relación, empezando por el que más fácilmente asumirías:", ["Larga distancia", "Cambiar de ciudad", "La desaprobación de la familia", "Una diferencia de edad"]]),
    ol("making_partner_happy",
      ["Partnerini en çok mutlu etmek için yapabileceklerini sırala:", ["Sürpriz bir tatil", "Uzun ve içten bir konuşma", "Eski bir anıyı yeniden yaşatmak", "Onun bir hayalini gerçekleştirmek"]],
      ["Rank what you'd do to make your partner happiest:", ["A surprise vacation", "A long, heartfelt talk", "Recreating an old memory", "Making one of their dreams come true"]],
      ["Ordena lo que harías para hacer más feliz a tu pareja:", ["Unas vacaciones sorpresa", "Una charla larga y sincera", "Recrear un recuerdo antiguo", "Cumplir uno de sus sueños"]]),
    ol("attractive_traits_partner",
      ["Partnerinde en çok çekici bulduğun özellikleri sırala:", ["Özgüveni", "Zekâsı ve mizahı", "Naziği ve ilgisi", "Tutkusu ve enerjisi"]],
      ["Rank the traits you find most attractive in your partner:", ["Their confidence", "Their intelligence and humor", "Their kindness and attentiveness", "Their passion and energy"]],
      ["Ordena los rasgos que más atractivos encuentras en tu pareja:", ["Su seguridad", "Su inteligencia y humor", "Su amabilidad y atención", "Su pasión y energía"]]),
    ol("relationship_hurts",
      ["Bir ilişkide en çok yaralayan şeyleri, en çok yaralayandan başlayarak sırala:", ["Güvenin sarsılması", "İlgisizlik", "Sürekli eleştiri", "Yalnız bırakılmak"]],
      ["Rank what hurts most in a relationship, starting with the most hurtful:", ["Broken trust", "Indifference", "Constant criticism", "Being left alone"]],
      ["Ordena lo que más daña en una relación, empezando por lo más doloroso:", ["Que se rompa la confianza", "La indiferencia", "La crítica constante", "Que te dejen solo"]]),
    ol("freedom_closeness",
      ["Özgürlük ile yakınlığı dengelemede önceliklerini sırala:", ["Kendi hobilerime vakit", "Arkadaşlarımla zaman", "Birlikte kaliteli zaman", "Düzenli ortak rutinler"]],
      ["Rank your priorities for balancing freedom and closeness:", ["Time for my own hobbies", "Time with my friends", "Quality time together", "Regular shared routines"]],
      ["Ordena tus prioridades para equilibrar libertad y cercanía:", ["Tiempo para mis aficiones", "Tiempo con mis amigos", "Tiempo de calidad juntos", "Rutinas compartidas regulares"]]),
    ol("never_do",
      ["Bir ilişkide asla yapmayacağın şeyleri, en kesin “asla” olandan başlayarak sırala:", ["Partnerimin mesajlarını gizlice okumak", "Başkasına yanlış umut vermek", "Önemli bir şeyi saklamak", "Partnerimi başkalarının önünde küçük düşürmek"]],
      ["Rank what you'd never do in a relationship, starting with your firmest “never”:", ["Secretly reading my partner's messages", "Giving someone else false hope", "Hiding something important", "Embarrassing my partner in front of others"]],
      ["Ordena lo que nunca harías en una relación, empezando por tu «jamás» más firme:", ["Leer a escondidas los mensajes de mi pareja", "Dar falsas esperanzas a otra persona", "Ocultar algo importante", "Avergonzar a mi pareja delante de otros"]]),
    ol("vulnerability_sharing",
      ["Sevdiğin biriyle paylaşabileceğin en kişisel şeyleri, en kolay paylaşacağından başlayarak sırala:", ["Geçmiş anılarım", "Korkularım", "Hayallerim", "Utandığım şeyler"]],
      ["Rank the most personal things you could share with someone you love, starting with the easiest:", ["My past memories", "My fears", "My dreams", "Things I'm embarrassed about"]],
      ["Ordena lo más personal que podrías compartir con alguien a quien quieres, empezando por lo más fácil:", ["Mis recuerdos del pasado", "Mis miedos", "Mis sueños", "Cosas que me avergüenzan"]]),
    ol("surprising_partner",
      ["Partnerini en çok şaşırtacak şeyleri sırala:", ["Doğaçlama bir yolculuk", "Gizlice hazırlanmış bir akşam", "Hiç beklemediği bir hediye", "Eski bir anıyı yeniden yaşatmak"]],
      ["Rank what would surprise your partner most:", ["A spontaneous trip", "A secretly arranged evening", "A totally unexpected gift", "Recreating an old memory"]],
      ["Ordena lo que más sorprendería a tu pareja:", ["Un viaje improvisado", "Una velada preparada en secreto", "Un regalo totalmente inesperado", "Recrear un recuerdo antiguo"]]),
  ],
};
