import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// İletişim — ortak (friend, dating, partner). Tür-bağımsız yazılmalı: ilişki/romantik çağrışım YOK.
export const communication: SeedCategory = {
  slug: "communication",
  names: { tr: "İletişim", en: "Communication", es: "Comunicación" },
  relationshipTypes: ["friend", "dating", "partner"],
  isPremium: false,
  sortOrder: 8,
  questions: [
    sc("conflict_cooling",
      "Bir tartışma sırasında önce biraz ara verip sakinleşmeyi tercih eder misin?",
      "During a disagreement, do you prefer to take a break and cool down first?",
      "En un desacuerdo, ¿prefieres tomarte un descanso y calmarte primero?"),
    sc("holding_in",
      "Canını sıkan bir şeyi, konuşmak yerine bir süre içinde tutmayı tercih eder misin?",
      "Do you tend to keep something that bothers you to yourself rather than bring it up?",
      "¿Tiendes a guardarte lo que te molesta en lugar de plantearlo?"),
    sc("apology",
      "Haklı olduğunu düşünsen bile, ortam gerildiğinde ilk özür dileyen sen olur musun?",
      "Even when you feel you're right, are you the first to apologize when things get tense?",
      "Aunque creas tener razón, ¿sueles ser quien se disculpa primero cuando la tensión sube?"),
    sc("listening",
      "Biri derdini anlatırken hemen çözüm önermek yerine sadece dinlemeyi seçer misin?",
      "When someone shares a problem, do you choose to just listen instead of jumping to solutions?",
      "Cuando alguien te cuenta un problema, ¿prefieres escuchar en lugar de ofrecer soluciones enseguida?"),
    sc("call_vs_text",
      "Önemli bir konuyu yazışmak yerine yüz yüze ya da telefonla konuşmayı tercih eder misin?",
      "Do you prefer to discuss something important face to face or by phone rather than by text?",
      "¿Prefieres hablar de algo importante en persona o por teléfono en vez de por mensaje?"),
    sc("feedback_receptivity",
      "Eleştiri aldığında ilk tepkin savunmaya geçmek yerine dinlemek olur mu?",
      "When you get criticism, is your first reaction to listen rather than get defensive?",
      "Cuando te critican, ¿tu primera reacción es escuchar en lugar de ponerte a la defensiva?"),
    sc("emotional_expression",
      "Duygularını kelimelere dökmek senin için kolay mı?",
      "Is putting your feelings into words easy for you?",
      "¿Te resulta fácil poner tus sentimientos en palabras?"),
    sc("silence_comfort",
      "Konuşmadan, sadece yan yana sessizce vakit geçirmek seni rahatlatır mı?",
      "Does spending time in comfortable silence with someone help you relax?",
      "¿Pasar tiempo en silencio junto a alguien te relaja?"),

    pr("conflict_style",
      ["Biriyle fikir ayrılığına düştün ve ortam gerildi. Genelde ne yaparsın?",
        ["Hemen açıkça konuşup çözmeye çalışırım", "Biraz uzaklaşır, sakinleşince dönerim", "Konuyu kapatmak için ben taviz veririm", "Haklı olduğumu anlatana kadar ısrar ederim"]],
      ["You've had a disagreement with someone and things got tense. What do you usually do?",
        ["Talk it out openly right away", "Step back and return once I've cooled down", "Give in to end the tension", "Keep pushing until they see I'm right"]],
      ["Has tenido un desacuerdo con alguien y el ambiente se ha tensado. ¿Qué sueles hacer?",
        ["Hablarlo abiertamente enseguida", "Alejarme un poco y volver cuando me calme", "Ceder yo para cerrar el tema", "Insistir hasta que vean que tengo razón"]]),
    pr("sharing_bad_news",
      ["Yaşadığın kötü bir olayı birine anlatman gerekiyor. Nasıl yaparsın?",
        ["Doğrudan ve açıkça anlatırım", "Önce ortamı yumuşatır, sonra söylerim", "Yazarak anlatmayı tercih ederim", "Mümkün olduğunca sonraya ertelerim"]],
      ["You need to tell someone about something bad that happened to you. How do you do it?",
        ["Directly and openly", "Soften the mood first, then say it", "In writing", "Put it off as long as I can"]],
      ["Tienes que contarle a alguien algo malo que te ha pasado. ¿Cómo lo haces?",
        ["De forma directa y abierta", "Suavizo el ambiente y luego lo cuento", "Por escrito", "Lo pospongo todo lo que puedo"]]),
    pr("hurt_response",
      ["Biri seni kırdığını fark etmeden davranmaya devam ediyor. Ne yaparsın?",
        ["Hemen söylerim", "Uygun bir an kollayıp konuşurum", "Davranışlarımla belli ederim, söylemem", "Zamanla geçer diye beklerim"]],
      ["Someone hurt you and doesn't realize it. What do you do?",
        ["Tell them right away", "Wait for the right moment to talk", "Show it through my behavior without saying it", "Wait for it to pass over time"]],
      ["Alguien te ha herido sin darse cuenta. ¿Qué haces?",
        ["Se lo digo enseguida", "Espero el momento adecuado para hablar", "Lo demuestro con mi actitud sin decirlo", "Espero a que se me pase con el tiempo"]]),
    pr("giving_feedback",
      ["Birine bir şeyi yanlış yaptığını söylemen gerekiyor. Yaklaşımın ne olur?",
        ["Net ve kısa söylerim", "Önce iyi yanlarını sayar, sonra söylerim", "Soru sorarak kendisinin fark etmesini sağlarım", "Çok gerekmedikçe söylemem"]],
      ["You need to tell someone they got something wrong. What's your approach?",
        ["Say it clearly and briefly", "Mention the positives first, then say it", "Ask questions so they notice it themselves", "Avoid saying it unless I really have to"]],
      ["Tienes que decirle a alguien que se ha equivocado. ¿Cuál es tu enfoque?",
        ["Lo digo claro y breve", "Primero destaco lo positivo y luego lo digo", "Hago preguntas para que se dé cuenta por su cuenta", "No lo digo a menos que sea necesario"]]),
    pr("comfort_style",
      ["Biri çok üzgün ve yanındasın. Ona nasıl destek olursun?",
        ["Sarılır, sessizce yanında dururum", "Sorunu birlikte çözmeye çalışırım", "Dikkatini dağıtacak bir şey yaparım", "Anlatmak isterse dinlerim, istemezse zorlamam"]],
      ["Someone is really upset and you're with them. How do you support them?",
        ["Hug them and stay by their side quietly", "Work through the problem together", "Do something to take their mind off it", "Listen if they want to talk, don't push if they don't"]],
      ["Alguien está muy mal y estás a su lado. ¿Cómo lo apoyas?",
        ["Lo abrazo y me quedo a su lado en silencio", "Intento resolver el problema juntos", "Hago algo para distraerle", "Escucho si quiere hablar y no insisto si no"]]),

    ol("communication_priorities",
      ["İyi bir iletişimde en önemli şeyleri sırala:", ["Dürüstlük", "Dinlemek", "Doğru zamanlama", "Nazik bir dil"]],
      ["Rank what matters most in good communication:", ["Honesty", "Listening", "Good timing", "Kind wording"]],
      ["Ordena lo más importante en una buena comunicación:", ["Honestidad", "Escuchar", "Buen momento", "Palabras amables"]]),
    ol("stress_reaction",
      ["Gerildiğinde başvurduğun yolları, en çok başvurduğundan başlayarak sırala:", ["Konuşarak rahatlamak", "Yalnız kalmak", "Hareket etmek ya da dışarı çıkmak", "Bir şeyle meşgul olup oyalanmak"]],
      ["Rank how you cope when you're tense, starting with what you do most:", ["Talking it out", "Being alone", "Moving or getting outside", "Keeping busy with something"]],
      ["Ordena cómo te calmas cuando estás tenso, empezando por lo que más haces:", ["Hablarlo", "Estar a solas", "Moverme o salir", "Mantenerme ocupado"]]),
    ol("message_habits",
      ["Mesajlaşma alışkanlıklarını, sana en çok uyandan başlayarak sırala:", ["Hemen cevap veririm", "Müsait olunca uzun uzun yazarım", "Sesli mesaj ya da arama tercih ederim", "Çoğu zaman geç dönerim"]],
      ["Rank your messaging habits, starting with the one that's most like you:", ["I reply right away", "I write long replies when I'm free", "I prefer voice notes or calls", "I usually reply late"]],
      ["Ordena tus hábitos de mensajería, empezando por el que más te define:", ["Respondo enseguida", "Escribo largo cuando tengo tiempo", "Prefiero audios o llamadas", "Suelo responder tarde"]]),
    ol("trust_builders",
      ["Bir insana güvenmeni sağlayan şeyleri sırala:", ["Sözünü tutması", "Samimi olması", "Zor zamanda yanında olması", "Sırlarını saklaması"]],
      ["Rank what makes you trust someone:", ["Keeping their word", "Being genuine", "Being there in hard times", "Keeping your secrets"]],
      ["Ordena lo que te hace confiar en alguien:", ["Que cumpla su palabra", "Que sea auténtico", "Que esté en los momentos difíciles", "Que guarde tus secretos"]]),

    // ── Tamamlama: her modda 10'a ──────────────────────────────────────
    sc("text_preference",
      "Telefonla konuşmak yerine mesajlaşmayı tercih eder misin?",
      "Do you prefer texting over talking on the phone?",
      "¿Prefieres escribir mensajes a hablar por teléfono?"),
    sc("speaking_up",
      "Bir grup içinde ya da toplantıda fikrini hemen söyler misin?",
      "In a group or meeting, do you voice your opinion right away?",
      "En un grupo o reunión, ¿das tu opinión enseguida?"),

    pr("harsh_words_reaction",
      ["Biri sana beklemediğin bir şekilde sert konuştu. Tepkin ne olur?",
        ["Sakin kalıp nedenini sorarım", "Ben de aynı tonla karşılık veririm", "Susar, içimden geçiririm", "O anı geçirip sonra konuşurum"]],
      ["Someone speaks harshly to you out of nowhere. How do you react?",
        ["Stay calm and ask why", "Respond in the same tone", "Go quiet and stew on it", "Let it pass and talk later"]],
      ["Alguien te habla con dureza de forma inesperada. ¿Cómo reaccionas?",
        ["Mantengo la calma y pregunto por qué", "Respondo en el mismo tono", "Me callo y le doy vueltas por dentro", "Lo dejo pasar y hablo más tarde"]]),
    pr("dissent_style",
      ["Bir konuda fikrin diğerlerinden farklı. Grupta ne yaparsın?",
        ["Açıkça savunurum", "Nazikçe belirtir, ısrar etmem", "Konuşmaz, çoğunluğa uyarım", "Sonradan birebir söylerim"]],
      ["Your opinion differs from everyone else's. What do you do in the group?",
        ["Defend it openly", "Mention it politely without pushing", "Stay quiet and go with the majority", "Say it one-on-one afterwards"]],
      ["Tu opinión es distinta a la de los demás. ¿Qué haces en el grupo?",
        ["La defiendo abiertamente", "La menciono con educación sin insistir", "Me callo y sigo a la mayoría", "Lo digo en privado después"]]),
    pr("correcting_others",
      ["Yakın biri başkalarının yanında yanlış bir bilgi verdi ve sen doğrusunu biliyorsun. Ne yaparsın?",
        ["Hemen düzeltirim", "Sonra ikimiz kalınca söylerim", "Nazikçe “Ben şöyle biliyordum” derim", "Önemli değilse üstünde durmam"]],
      ["Someone close to you states something wrong in front of others, and you know the truth. What do you do?",
        ["Correct them right away", "Tell them privately afterwards", "Gently say “I thought it was...”", "Let it go if it doesn't matter"]],
      ["Alguien cercano dice algo incorrecto delante de otros y tú sabes la verdad. ¿Qué haces?",
        ["Lo corrijo enseguida", "Se lo digo en privado después", "Digo con tacto «yo pensaba que era...»", "Lo dejo pasar si no importa"]]),
    pr("meeting_behavior",
      ["Bir sorunu çözmek için toplandınız ve herkes aynı anda konuşuyor. Sen ne yaparsın?",
        ["Söz isteyip düzeni sağlarım", "Sessizce dinleyip notlar alırım", "Ben de araya girip sesimi yükseltirim", "Fikrimi sonradan yazılı bildiririm"]],
      ["In a meeting to solve a problem, everyone's talking at once. What do you do?",
        ["Ask for the floor and restore order", "Listen quietly and take notes", "Jump in and raise my voice too", "Share my ideas in writing afterwards"]],
      ["En una reunión para resolver un problema, todos hablan a la vez. ¿Qué haces?",
        ["Pido la palabra y pongo orden", "Escucho en silencio y tomo notas", "Me meto y levanto la voz yo también", "Envío mis ideas por escrito después"]]),
    pr("delivering_bad_news",
      ["Birine onu üzecek bir haberi vermen gerekiyor. Ne zaman söylersin?",
        ["Hemen, ne kadar erken o kadar iyi", "Uygun, sakin bir an kollarım", "Mümkün olan en son ana kadar bekletirim", "Başkasının söylemesini umarım"]],
      ["You have to give someone news that will upset them. When do you tell them?",
        ["Right away, the sooner the better", "Wait for a calm, suitable moment", "Delay until the last possible moment", "Hope someone else tells them"]],
      ["Tienes que dar a alguien una noticia que le va a disgustar. ¿Cuándo se la dices?",
        ["Enseguida, cuanto antes mejor", "Espero un momento tranquilo y adecuado", "La retraso hasta el último momento", "Espero que se lo diga otra persona"]]),

    ol("conversation_irritants",
      ["Bir konuşmada seni en çok rahatsız eden şeyleri, en çok rahatsız edenden başlayarak sırala:", ["Lafının kesilmesi", "Dinlenmediğini hissetmek", "Sesin yükselmesi", "Alaycı bir üslup"]],
      ["Rank what bothers you most in a conversation, starting with the biggest irritant:", ["Being interrupted", "Feeling unheard", "Raised voices", "A sarcastic tone"]],
      ["Ordena lo que más te molesta en una conversación, empezando por lo peor:", ["Que te interrumpan", "Sentirte ignorado", "Que suban la voz", "Un tono sarcástico"]]),
    ol("channel_preference",
      ["İletişim kurarken tercih ettiğin yolları sırala:", ["Yüz yüze konuşma", "Telefon görüşmesi", "Sesli mesaj", "Yazılı mesaj"]],
      ["Rank your preferred ways to communicate:", ["Face to face", "Phone call", "Voice message", "Text message"]],
      ["Ordena tus formas preferidas de comunicarte:", ["En persona", "Llamada telefónica", "Mensaje de voz", "Mensaje escrito"]]),
    ol("conflict_steps",
      ["Bir sorunu çözmek için hangi adımlara öncelik verirsin? Sırala:", ["Sakinleşmek", "Karşı tarafı dinlemek", "Kendi görüşümü açıklamak", "Ortak bir çözüm aramak"]],
      ["Which steps do you prioritize to solve a problem? Rank:", ["Calming down", "Listening to the other side", "Explaining my view", "Looking for a shared solution"]],
      ["¿Qué pasos priorizas para resolver un problema? Ordena:", ["Calmarme", "Escuchar a la otra parte", "Explicar mi punto de vista", "Buscar una solución común"]]),
    ol("feedback_style",
      ["Sana verilebilecek en değerli geri bildirim türlerini sırala:", ["Açık ve doğrudan", "Örneklerle desteklenen", "Nazik ve cesaretlendirici", "Çözüm önerisi içeren"]],
      ["Rank the kinds of feedback that are most valuable to you:", ["Clear and direct", "Backed by examples", "Kind and encouraging", "Including suggested solutions"]],
      ["Ordena los tipos de comentarios más valiosos para ti:", ["Claros y directos", "Respaldados con ejemplos", "Amables y alentadores", "Con propuestas de solución"]]),
    ol("motivating_words",
      ["Duymanın seni en çok motive ettiği sözleri sırala:", ["Teşekkür edilmesi", "Takdir edilmek", "Güvenildiğini duymak", "Gelişimimin fark edilmesi"]],
      ["Rank the words that motivate you most to hear:", ["Being thanked", "Being appreciated", "Hearing that I'm trusted", "Having my progress noticed"]],
      ["Ordena lo que más te motiva escuchar:", ["Que me den las gracias", "Que me valoren", "Oír que confían en mí", "Que noten mi progreso"]]),
    ol("hard_conversation_prep",
      ["Zor bir konuşmaya hazırlanırken önceliklerini sırala:", ["Ne söyleyeceğimi planlamak", "Sakin kalmak", "Karşı tarafı anlamaya çalışmak", "Doğru zamanı seçmek"]],
      ["Rank your priorities when preparing for a difficult conversation:", ["Planning what to say", "Staying calm", "Trying to understand the other side", "Picking the right time"]],
      ["Ordena tus prioridades al preparar una conversación difícil:", ["Planificar qué decir", "Mantener la calma", "Intentar entender a la otra parte", "Elegir el momento adecuado"]]),
  ],
};
