import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Tanışma (eski "İlk Adım", slug first_date) — yalnızca "dating". Sıcak, hafif, flörtöz ama açık/müstehcen değil.
export const firstDate: SeedCategory = {
  slug: "first_date",
  names: { tr: "Tanışma", en: "Getting to Know You", es: "Conociéndonos" },
  relationshipTypes: ["dating"],
  isPremium: false,
  sortOrder: 3,
  questions: [
    sc("date_outfit",
      "İlk buluşmaya hazırlanırken ne giyeceğine uzun süre karar veremez misin?",
      "When getting ready for a first date, do you struggle for ages to decide what to wear?",
      "Al prepararte para una primera cita, ¿tardas mucho en decidir qué ponerte?"),
    sc("nervous_talking",
      "İlk buluşmada heyecanlanınca daha çok konuşur musun?",
      "When you're nervous on a first date, do you end up talking more?",
      "Cuando te pones nervioso en una primera cita, ¿acabas hablando más?"),
    sc("showing_interest",
      "Birine ilgi duyduğunda bunu ona hemen belli eder misin?",
      "When you're interested in someone, do you show it right away?",
      "Cuando alguien te interesa, ¿se lo demuestras enseguida?"),
    sc("offer_to_pay",
      "İlk buluşmada hesabı ödemeyi teklif etmek senin için doğal mı?",
      "Is offering to pay on a first date natural for you?",
      "¿Te resulta natural ofrecerte a pagar en una primera cita?"),
    sc("early_texting_restraint",
      "Yeni tanıştığın birine ilk günlerde sürekli mesaj atmaktan çekinir misin?",
      "Do you hold back from texting someone constantly in the early days?",
      "¿Te contienes de escribirle a alguien constantemente en los primeros días?"),
    sc("laugh_at_self",
      "İlk buluşmada kendinle dalga geçebilir misin?",
      "On a first date, can you laugh at yourself?",
      "En una primera cita, ¿sabes reírte de ti mismo?"),
    sc("tell_friends",
      "Bir buluşmanın nasıl geçtiğini sonrasında arkadaşlarına ayrıntılı anlatır mısın?",
      "After a date, do you tell your friends all the details?",
      "Después de una cita, ¿les cuentas todos los detalles a tus amigos?"),
    sc("impression_can_change",
      "İlk izlenimin sonradan değişebileceğine inanır mısın?",
      "Do you believe a first impression can change later?",
      "¿Crees que la primera impresión puede cambiar después?"),
    sc("humor_to_impress",
      "Hoşuna giden birini güldürmek için espri yapmaya çalışır mısın?",
      "Do you try to be funny to make someone you like laugh?",
      "¿Intentas hacer bromas para que alguien que te gusta se ría?"),
    sc("waiting_rules",
      "İlk buluşmadan sonra ertesi gün mesaj atmadan önce beklemek gerektiğine inanır mısın?",
      "Do you believe you should wait before texting the day after a first date?",
      "¿Crees que hay que esperar antes de escribir al día siguiente de una primera cita?"),

    pr("first_date_pick",
      ["İlk buluşma için nerede görüşmeyi tercih edersin?",
        ["Sakin bir kafe", "Birlikte bir aktivite (müze, yürüyüş)", "Güzel bir restoran", "Eğlenceli bir mekân (bowling, oyun salonu)"]],
      ["Where would you prefer to meet for a first date?",
        ["A quiet café", "A shared activity (museum, walk)", "A nice restaurant", "A fun spot (bowling, arcade)"]],
      ["¿Dónde preferirías quedar para una primera cita?",
        ["Una cafetería tranquila", "Una actividad juntos (museo, paseo)", "Un buen restaurante", "Un sitio divertido (bolera, recreativos)"]]),
    pr("early_texting",
      ["Yeni tanıştığın biriyle ilk günlerde yazışma sıklığın nasıl olur?",
        ["Gün boyu sık sık yazışırız", "Günde bir iki kez uzun yazışırız", "Daha çok sesli konuşmayı severim", "Karşı tarafın temposuna uyarım"]],
      ["How often do you text someone in the early days after meeting?",
        ["Often throughout the day", "One or two long chats a day", "I prefer calling or voice notes", "I match their pace"]],
      ["¿Con qué frecuencia escribes a alguien en los primeros días tras conoceros?",
        ["A menudo durante el día", "Una o dos conversaciones largas al día", "Prefiero llamar o enviar audios", "Me adapto a su ritmo"]]),
    pr("compliment_response",
      ["Biri sana beklemediğin bir iltifat etti. Nasıl karşılık verirsin?",
        ["Gülümseyip teşekkür ederim", "Utanıp espriyle geçiştiririm", "Ben de ona bir iltifat ederim", "Biraz kızarır, konuyu değiştiririm"]],
      ["Someone gives you an unexpected compliment. How do you respond?",
        ["Smile and say thanks", "Get shy and brush it off with a joke", "Compliment them back", "Blush a bit and change the subject"]],
      ["Alguien te hace un cumplido inesperado. ¿Cómo respondes?",
        ["Sonrío y doy las gracias", "Me da vergüenza y lo paso con una broma", "Le devuelvo el cumplido", "Me sonrojo un poco y cambio de tema"]]),
    pr("phone_on_date",
      ["İlk buluşmada karşındaki sürekli telefonuna bakıyor. Ne yaparsın?",
        ["Nazikçe fark ettiririm", "Bir şey demem ama aklıma yazarım", "Ben de telefonuma bakarım", "Buluşmayı erken bitiririm"]],
      ["On a first date, the other person keeps checking their phone. What do you do?",
        ["Gently point it out", "Say nothing but make a mental note", "Check my own phone too", "End the date early"]],
      ["En una primera cita, la otra persona no deja de mirar el móvil. ¿Qué haces?",
        ["Se lo hago notar con delicadeza", "No digo nada, pero lo tengo en cuenta", "Miro yo también mi móvil", "Acabo la cita antes"]]),
    pr("after_first_date",
      ["İlk buluşma iyi geçti. Sonrasında ne yaparsın?",
        ["Hemen mesaj atıp teşekkür ederim", "Bir gün bekleyip yazarım", "Karşı tarafın yazmasını beklerim", "Hemen ikinci buluşmayı teklif ederim"]],
      ["The first date went well. What do you do afterwards?",
        ["Text right away to say thanks", "Wait a day, then write", "Wait for them to text first", "Suggest a second date straight away"]],
      ["La primera cita fue bien. ¿Qué haces después?",
        ["Escribo enseguida para dar las gracias", "Espero un día y escribo", "Espero a que escriba primero", "Propongo una segunda cita de inmediato"]]),
    pr("date_prep",
      ["İlk buluşmaya giderken ne kadar hazırlanırsın?",
        ["Saatlerce hazırlanırım", "Hızlıca, rahat bir şekilde", "En sevdiğim kıyafeti giyip çıkarım", "Hiç hazırlanmam, olduğum gibi giderim"]],
      ["How much do you prepare for a first date?",
        ["I take hours getting ready", "Quickly and casually", "Wear my favorite outfit and go", "Not at all, I go as I am"]],
      ["¿Cuánto te preparas para una primera cita?",
        ["Me paso horas arreglándome", "Rápido y sin complicaciones", "Me pongo mi ropa favorita y salgo", "Nada, voy tal como soy"]]),
    pr("awkward_silence",
      ["İlk buluşmada ortam bir anda sessizleşti. Ne yaparsın?",
        ["Bir soru sorarak sohbeti yeniden başlatırım", "Sessizliğin tadını çıkarırım", "Espriyle ortamı hareketlendiririm", "Biraz heyecanlanıp telefonuma bakarım"]],
      ["Things go quiet on a first date. What do you do?",
        ["Ask a question to restart the conversation", "Enjoy the silence", "Liven things up with a joke", "Get nervous and check my phone"]],
      ["Se hace el silencio en una primera cita. ¿Qué haces?",
        ["Hago una pregunta para retomar la conversación", "Disfruto del silencio", "Animo el ambiente con una broma", "Me pongo nervioso y miro el móvil"]]),
    pr("personal_question",
      ["Karşındaki, ilk buluşmada sana çok kişisel bir soru sordu. Ne yaparsın?",
        ["Açıkça cevaplarım", "Kısa cevap verip konuyu değiştiririm", "Aynı soruyu ona sorarım", "Biraz çekinir, “sonra anlatırım” derim"]],
      ["Someone asks you a very personal question on a first date. What do you do?",
        ["Answer openly", "Give a short answer and change the subject", "Ask them the same question back", "Feel shy and say “I'll tell you later”"]],
      ["Alguien te hace una pregunta muy personal en una primera cita. ¿Qué haces?",
        ["Respondo con franqueza", "Respondo breve y cambio de tema", "Le hago la misma pregunta a esa persona", "Me corto y digo «ya te lo contaré»"]]),
    pr("shared_interest",
      ["Yeni tanıştığın biriyle ortak bir ilgi alanınız olduğunu fark ettin. Ne yaparsın?",
        ["Hemen konuyu açıp heyecanla konuşurum", "Sakince belirtirim", "Bununla ilgili birlikte yapabileceğimiz bir şey öneririm", "Aklımda tutar, sonraya saklarım"]],
      ["You discover you share an interest with someone you just met. What do you do?",
        ["Bring it up right away and talk excitedly", "Mention it calmly", "Suggest doing something together related to it", "Make a mental note and save it for later"]],
      ["Descubres que compartes una afición con alguien que acabas de conocer. ¿Qué haces?",
        ["Lo saco enseguida y hablo con entusiasmo", "Lo menciono con calma", "Propongo hacer algo juntos relacionado", "Lo apunto mentalmente y lo guardo para después"]]),
    pr("goodbye_style",
      ["İlk buluşmanın sonunda vedalaşma anı geldi. Nasıl vedalaşırsın?",
        ["Sıcak bir sarılma ile", "Gülümseyip el sallayarak", "Bir sonraki plan hakkında konuşarak", "Kısa ve nazik bir teşekkürle"]],
      ["It's time to say goodbye at the end of a first date. How do you do it?",
        ["With a warm hug", "With a smile and a wave", "By talking about a next plan", "With a short, polite thank you"]],
      ["Llega el momento de despedirse al final de una primera cita. ¿Cómo lo haces?",
        ["Con un abrazo cálido", "Con una sonrisa y un saludo", "Hablando de un próximo plan", "Con un breve y educado agradecimiento"]]),

    ol("first_impression_traits",
      ["Yeni tanıştığın birinde ilk izlenimde en çok neye dikkat edersin? Sırala:", ["Gülüşü ve enerjisi", "Konuşma tarzı", "Mizah anlayışı", "Samimiyeti"]],
      ["What do you notice most in someone you've just met? Rank:", ["Their smile and energy", "Their way of speaking", "Their sense of humor", "Their sincerity"]],
      ["¿En qué te fijas más en alguien que acabas de conocer? Ordena:", ["Su sonrisa y energía", "Su forma de hablar", "Su sentido del humor", "Su sinceridad"]]),
    ol("date_priorities",
      ["Mükemmel bir ilk buluşma için önceliklerini sırala:", ["Rahat bir ortam", "Akıcı sohbet", "Eğlenceli bir aktivite", "Güzel yemek"]],
      ["Rank your priorities for a perfect first date:", ["A relaxed setting", "Easy conversation", "A fun activity", "Good food"]],
      ["Ordena tus prioridades para una primera cita perfecta:", ["Un ambiente relajado", "Conversación fluida", "Una actividad divertida", "Buena comida"]]),
    ol("connection_cues",
      ["Biriyle bağ kurduğunu hissettiren şeyleri sırala:", ["Ortak mizah", "Benzer değerler", "Birbirini dinlemek", "Ortak ilgi alanları"]],
      ["Rank what makes you feel a connection with someone:", ["Shared humor", "Similar values", "Listening to each other", "Shared interests"]],
      ["Ordena lo que te hace sentir conexión con alguien:", ["Humor compartido", "Valores similares", "Escucharse mutuamente", "Intereses en común"]]),
    ol("early_turn_offs",
      ["İlk buluşmada seni en çok soğutacak şeyleri, en çok soğutandan başlayarak sırala:", ["Sürekli telefonla ilgilenmek", "Sadece kendinden bahsetmek", "Garsona kaba davranmak", "Hiç soru sormamak"]],
      ["Rank what would put you off most on a first date, starting with the biggest turn-off:", ["Constantly being on the phone", "Only talking about themselves", "Being rude to the waiter", "Never asking questions"]],
      ["Ordena lo que más te echaría atrás en una primera cita, empezando por lo peor:", ["Estar siempre con el móvil", "Hablar solo de sí mismo", "Ser maleducado con el camarero", "No hacer nunca preguntas"]]),
    ol("first_date_topics",
      ["İlk buluşmada konuşmak isteyeceğin konuları sırala:", ["Hobiler ve ilgi alanları", "Seyahat anıları", "Aile ve arkadaşlar", "Gelecek hayalleri"]],
      ["Rank the topics you'd want to talk about on a first date:", ["Hobbies and interests", "Travel memories", "Family and friends", "Future dreams"]],
      ["Ordena los temas de los que querrías hablar en una primera cita:", ["Aficiones e intereses", "Recuerdos de viajes", "Familia y amigos", "Sueños de futuro"]]),
    ol("date_venues",
      ["İlk buluşma için tercih edeceğin yerleri sırala:", ["Kafe", "Park ya da sahilde yürüyüş", "Restoran", "Sinema"]],
      ["Rank the places you'd pick for a first date:", ["Café", "A walk in the park or by the sea", "Restaurant", "Cinema"]],
      ["Ordena los lugares que elegirías para una primera cita:", ["Cafetería", "Paseo por el parque o la playa", "Restaurante", "Cine"]]),
    ol("attention_cues",
      ["Karşındaki kişide ilk dikkatini çeken davranışları sırala:", ["Göz teması kurması", "Dinlemesi", "Nazik olması", "Kendinden emin olması"]],
      ["Rank the behaviors that first catch your attention in someone:", ["Making eye contact", "Listening", "Being kind", "Being confident"]],
      ["Ordena los comportamientos que primero te llaman la atención en alguien:", ["Mantener el contacto visual", "Escuchar", "Ser amable", "Mostrar seguridad"]]),
    ol("getting_to_know_questions",
      ["Birini daha iyi tanımak için sorabileceğin soruları öncelik sırasına göre sırala:", ["En sevdiği yerler", "Hayattaki hedefleri", "Çocukluk anıları", "Boş zaman alışkanlıkları"]],
      ["Rank the questions you'd ask to get to know someone better:", ["Their favorite places", "Their life goals", "Childhood memories", "Their free-time habits"]],
      ["Ordena las preguntas que harías para conocer mejor a alguien:", ["Sus lugares favoritos", "Sus metas en la vida", "Recuerdos de la infancia", "Sus hábitos en el tiempo libre"]]),
    ol("at_ease_factors",
      ["Bir buluşmada seni rahatlatan şeyleri sırala:", ["Samimi bir gülümseme", "Rahat bir ortam", "Ortak bir espri", "Dinlendiğimi hissetmek"]],
      ["Rank what puts you at ease on a date:", ["A warm smile", "A relaxed setting", "A shared joke", "Feeling listened to"]],
      ["Ordena lo que te tranquiliza en una cita:", ["Una sonrisa cálida", "Un ambiente relajado", "Una broma compartida", "Sentirme escuchado"]]),
    ol("second_date_factors",
      ["İkinci buluşma kararında en çok etkili olan şeyleri sırala:", ["Sohbetin akışı", "Hissettiğim enerji", "Ortak değerler", "Eğlenmiş olmam"]],
      ["Rank what most influences your decision to go on a second date:", ["How the conversation flowed", "The energy I felt", "Shared values", "Having had fun"]],
      ["Ordena lo que más influye en tu decisión de tener una segunda cita:", ["Cómo fluyó la conversación", "La energía que sentí", "Valores compartidos", "Haberlo pasado bien"]]),
  ],
};
