import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Birlikte Gelecek — yalnızca "partner" (Hayat Arkadaşı). Ortak plan, hayal ve hedefler.
export const future: SeedCategory = {
  slug: "future",
  names: { tr: "Birlikte Gelecek", en: "Future Together", es: "Futuro juntos" },
  relationshipTypes: ["partner"],
  isPremium: false,
  sortOrder: 5,
  questions: [
    sc("five_year_vision",
      "Beş yıl sonrasını net olarak hayal edebilir misin?",
      "Can you clearly picture yourself five years from now?",
      "¿Puedes imaginarte con claridad dentro de cinco años?"),
    sc("move_for_dreams",
      "Hayallerin için yaşadığın şehri değiştirmeye hazır mısın?",
      "Are you ready to move cities for your dreams?",
      "¿Estás dispuesto a cambiar de ciudad por tus sueños?"),
    sc("decide_together",
      "Büyük kararları (taşınma, iş değişikliği) birlikte almak senin için vazgeçilmez mi?",
      "Is making big decisions (moving, changing jobs) together essential for you?",
      "¿Es imprescindible para ti tomar juntos las grandes decisiones (mudanza, cambio de trabajo)?"),
    sc("long_term_sacrifice",
      "Ortak bir uzun vadeli hedef için fedakârlık yapmaya razı olur musun?",
      "Would you make sacrifices for a long-term goal you share?",
      "¿Estarías dispuesto a hacer sacrificios por una meta común a largo plazo?"),
    sc("quiet_town",
      "Yaşlandığında huzurlu, küçük bir kasabada yaşamayı hayal eder misin?",
      "Do you dream of living in a peaceful small town when you're older?",
      "¿Sueñas con vivir en un pueblo tranquilo cuando seas mayor?"),
    sc("yearly_learning",
      "Her yıl birlikte yeni bir şey öğrenmeyi (dil, hobi) hedeflemek ister misin?",
      "Would you like to set a yearly goal of learning something new together (a language, a hobby)?",
      "¿Te gustaría proponerte cada año aprender algo nuevo juntos (un idioma, una afición)?"),
    sc("writing_plans",
      "Gelecek planlarını yazıya dökmek seni motive eder mi?",
      "Does writing down your future plans motivate you?",
      "¿Te motiva escribir tus planes de futuro?"),
    sc("living_abroad",
      "Birlikte yurt dışında yaşama fikri seni heyecanlandırır mı?",
      "Does the idea of living abroad together excite you?",
      "¿Te emociona la idea de vivir juntos en el extranjero?"),
    sc("buying_home",
      "Birlikte bir ev satın almak seni heyecanlandırır mı?",
      "Does buying a home together excite you?",
      "¿Te ilusiona la idea de comprar una casa juntos?"),
    sc("shared_pet",
      "Birlikte bir evcil hayvana bakmak ister misin?",
      "Would you like to care for a pet together?",
      "¿Te gustaría cuidar juntos de una mascota?"),

    pr("dream_home",
      ["Hayalindeki ev hangisine daha yakın?",
        ["Şehir merkezinde, hareketli bir daire", "Sakin bir mahallede müstakil ev", "Doğayla iç içe, kırsalda bir ev", "Her yıl değiştirebileceğimiz kiralık evler"]],
      ["Which is closest to your dream home?",
        ["A lively apartment in the city center", "A detached house in a quiet neighborhood", "A house in the countryside, close to nature", "Rentals we can change every year"]],
      ["¿Cuál se parece más a tu casa soñada?",
        ["Un piso animado en el centro", "Una casa independiente en un barrio tranquilo", "Una casa en el campo, cerca de la naturaleza", "Alquileres que podamos cambiar cada año"]]),
    pr("job_offer_abroad",
      ["Birlikte yaşadığın kişiyle yurt dışında harika bir iş teklifini konuşuyorsunuz. Sen ne yaparsın?",
        ["Heyecanla hemen kabul etmek isterim", "Artıları ve eksileri uzun uzun listelerim", "Önce ailemizle ve çevremizle konuşurum", "Şu anki düzenimizi bozmak istemem"]],
      ["You two are discussing a great job offer abroad. What do you do?",
        ["Want to accept it excitedly right away", "List the pros and cons at length", "Talk with family and friends first", "Prefer not to disrupt our current life"]],
      ["Estáis hablando de una gran oferta de trabajo en el extranjero. ¿Qué haces?",
        ["Querría aceptarla con ilusión enseguida", "Hago una lista larga de pros y contras", "Hablo primero con la familia y amigos", "Prefiero no alterar nuestra vida actual"]]),
    pr("retirement_dream",
      ["Emekli olduğunda hayalin nedir?",
        ["Dünyayı gezmek", "Küçük bir bahçede sakin bir yaşam", "Yeni bir iş ya da hobiyle uğraşmak", "Ailemle ve yakınlarımla vakit geçirmek"]],
      ["What's your dream for retirement?",
        ["Traveling the world", "A quiet life with a small garden", "Taking up a new job or hobby", "Spending time with family and loved ones"]],
      ["¿Cuál es tu sueño para la jubilación?",
        ["Viajar por el mundo", "Una vida tranquila con un pequeño jardín", "Dedicarme a un nuevo trabajo o afición", "Pasar tiempo con la familia y mis seres queridos"]]),
    pr("planning_style_future",
      ["Gelecek için plan yapma konusunda nasılsın?",
        ["Detaylı bir yol haritası çizerim", "Genel hedefler koyarım, detayı akışa bırakırım", "Günü yaşarım, fazla plan yapmam", "Planı karşı tarafın yapmasını isterim"]],
      ["How are you with planning for the future?",
        ["I draw a detailed roadmap", "I set general goals and leave the details", "I live in the moment and plan little", "I'd rather the other person plans"]],
      ["¿Cómo llevas planificar el futuro?",
        ["Dibujo una hoja de ruta detallada", "Fijo metas generales y dejo los detalles", "Vivo el momento y planifico poco", "Prefiero que planifique la otra persona"]]),
    pr("traditions",
      ["Yıllık kutlama ve geleneklerinizi nasıl sürdürmek istersin?",
        ["Her yıl aynı gelenekleri koruyarak", "Her yıl yeni bir şey deneyerek", "Ailelerimizin geleneklerini birleştirerek", "Çok önemsemeden, o anki ruh haline göre"]],
      ["How would you like to keep up your yearly celebrations and traditions?",
        ["Keep the same traditions every year", "Try something new each year", "Blend our families' traditions", "Not make a big deal of it, go with the mood"]],
      ["¿Cómo te gustaría vivir vuestras celebraciones y tradiciones anuales?",
        ["Mantener las mismas tradiciones cada año", "Probar algo nuevo cada año", "Combinar las tradiciones de nuestras familias", "Sin darle mucha importancia, según el ánimo"]]),
    pr("home_priority",
      ["Birlikte yaşayacağınız evi seçiyorsunuz. Önceliğin ne olur?",
        ["Konum ve ulaşım", "Evin büyüklüğü", "Mahalle ve çevre", "Kira ya da fiyat"]],
      ["You're choosing a home to live in together. What's your priority?",
        ["Location and transport", "Size of the home", "Neighborhood and surroundings", "Rent or price"]],
      ["Estáis eligiendo una casa para vivir juntos. ¿Cuál es tu prioridad?",
        ["Ubicación y transporte", "Tamaño de la vivienda", "Barrio y entorno", "Alquiler o precio"]]),
    pr("five_years_where",
      ["Beş yıl sonra kendinizi nerede görüyorsunuz?",
        ["Aynı şehirde, aynı düzende", "Daha büyük bir şehirde", "Yurt dışında", "Daha sakin bir yerde"]],
      ["Where do you see yourselves in five years?",
        ["In the same city, same routine", "In a bigger city", "Abroad", "Somewhere quieter"]],
      ["¿Dónde os veis dentro de cinco años?",
        ["En la misma ciudad, con la misma rutina", "En una ciudad más grande", "En el extranjero", "En un lugar más tranquilo"]]),
    pr("goal_vs_opportunity",
      ["Birlikte bir hedef için tasarruf ediyorsunuz ama bir fırsat çıktı. Ne yaparsın?",
        ["Hedefe sadık kalırım", "Fırsatı değerlendirir, hedefi biraz erteleriz", "Birlikte oturup karar veririz", "Ayrı bir bütçe ayırabilir miyiz diye bakarım"]],
      ["You're saving together for a goal, but an opportunity comes up. What do you do?",
        ["Stick to the goal", "Take the opportunity and delay the goal a bit", "Sit down together and decide", "See if we can set aside a separate budget"]],
      ["Estáis ahorrando juntos para una meta, pero surge una oportunidad. ¿Qué haces?",
        ["Me mantengo fiel a la meta", "Aprovecho la oportunidad y aplazamos algo la meta", "Nos sentamos juntos a decidir", "Veo si podemos apartar un presupuesto aparte"]]),
    pr("lasting_habits",
      ["Yıllar sonra birlikte hangi alışkanlığı sürdürmek istersin?",
        ["Her akşam birlikte yemek", "Yıllık bir seyahat", "Haftalık bir gezi günü", "Her gün kısa bir yürüyüş"]],
      ["Years from now, which habit would you like to keep together?",
        ["Dinner together every evening", "A yearly trip", "A weekly outing day", "A short walk every day"]],
      ["Dentro de años, ¿qué hábito te gustaría conservar juntos?",
        ["Cenar juntos cada noche", "Un viaje anual", "Un día de salida semanal", "Un breve paseo cada día"]]),
    pr("big_change",
      ["Hayatınızda büyük bir değişiklik (taşınma, yeni iş) yaklaşıyor. Nasıl yaklaşırsın?",
        ["Heyecanla karşılarım", "Her ayrıntıyı planlarım", "Endişelenirim ama birlikte aşarız derim", "Mümkünse erteleyip beklerim"]],
      ["A big life change (a move, a new job) is coming up. How do you approach it?",
        ["Welcome it with excitement", "Plan every detail", "Worry, but trust we'll get through it together", "Postpone it if possible and wait"]],
      ["Se acerca un gran cambio en vuestra vida (mudanza, trabajo). ¿Cómo lo afrontas?",
        ["Con ilusión", "Planificando cada detalle", "Me preocupo, pero confío en que lo superaremos juntos", "Lo aplazo si puedo y espero"]]),

    ol("life_goals",
      ["Önümüzdeki on yıl için hedeflerini sırala:", ["Kariyerde ilerlemek", "Maddi güvence", "Birlikte seyahat etmek", "Kendi evimiz"]],
      ["Rank your goals for the next ten years:", ["Advancing in my career", "Financial security", "Traveling together", "Having our own home"]],
      ["Ordena tus objetivos para los próximos diez años:", ["Avanzar en mi carrera", "Seguridad económica", "Viajar juntos", "Tener nuestra propia casa"]]),
    ol("shared_priorities",
      ["Birlikte kurduğunuz hayatta en çok korumak istediğin şeyleri sırala:", ["Birlikte vakit geçirmek", "Kişisel özgürlük", "Ev düzeni", "Arkadaş ve aile bağları"]],
      ["Rank what you most want to protect in the life you've built together:", ["Time together", "Personal freedom", "Home routines", "Friendships and family ties"]],
      ["Ordena lo que más quieres proteger de la vida que habéis construido juntos:", ["El tiempo juntos", "La libertad personal", "La rutina del hogar", "Las amistades y la familia"]]),
    ol("big_dreams",
      ["Birlikte gerçekleştirmek istediğin hayalleri, en çok istediğinden başlayarak sırala:", ["Dünya turu", "Bir iş kurmak", "Kırsalda bir ev", "Yeni bir dil ya da meslek öğrenmek"]],
      ["Rank the dreams you'd most like to achieve together, starting with your top one:", ["A trip around the world", "Starting a business", "A house in the countryside", "Learning a new language or profession"]],
      ["Ordena los sueños que más te gustaría cumplir juntos, empezando por el principal:", ["Dar la vuelta al mundo", "Montar un negocio", "Una casa en el campo", "Aprender un idioma o una profesión nueva"]]),
    ol("future_worries",
      ["Gelecekle ilgili seni en çok düşündüren konuları sırala:", ["Sağlık", "Para", "İş güvencesi", "Zamanın hızlı geçmesi"]],
      ["Rank the things about the future that worry you most:", ["Health", "Money", "Job security", "Time passing too fast"]],
      ["Ordena lo que más te preocupa del futuro:", ["La salud", "El dinero", "La estabilidad laboral", "Que el tiempo pase demasiado rápido"]]),
    ol("future_trips",
      ["Gelecekte birlikte yapmak istediğin yolculukları sırala:", ["Kuzey ışıkları", "Kültür turu", "Kamp ve doğa", "Egzotik bir ada"]],
      ["Rank the trips you'd like to take together in the future:", ["Northern lights", "A cultural tour", "Camping and nature", "An exotic island"]],
      ["Ordena los viajes que te gustaría hacer juntos en el futuro:", ["Auroras boreales", "Un viaje cultural", "Camping y naturaleza", "Una isla exótica"]]),
    ol("home_features",
      ["Birlikte yaşayacağınız evde olmazsa olmazları sırala:", ["Geniş bir salon", "Bahçe ya da balkon", "Çalışma odası", "Açık mutfak"]],
      ["Rank the must-haves in the home you'll share:", ["A spacious living room", "A garden or balcony", "A study", "An open kitchen"]],
      ["Ordena los imprescindibles de la casa que compartiréis:", ["Un salón amplio", "Jardín o balcón", "Un despacho", "Una cocina abierta"]]),
    ol("learn_together",
      ["Önümüzdeki yıllarda birlikte öğrenmek istediğin şeyleri sırala:", ["Yeni bir dil", "Bir enstrüman", "Yemek yapma sanatı", "Bir spor dalı"]],
      ["Rank what you'd like to learn together in the coming years:", ["A new language", "An instrument", "The art of cooking", "A sport"]],
      ["Ordena lo que te gustaría aprender juntos en los próximos años:", ["Un idioma nuevo", "Un instrumento", "El arte de cocinar", "Un deporte"]]),
    ol("future_values",
      ["Bir gelecek planında en çok önem verdiğin değerleri sırala:", ["Güvenlik", "Özgürlük", "Büyüme", "Huzur"]],
      ["Rank the values you care about most in a plan for the future:", ["Security", "Freedom", "Growth", "Peace"]],
      ["Ordena los valores que más te importan en un plan de futuro:", ["Seguridad", "Libertad", "Crecimiento", "Tranquilidad"]]),
    ol("long_term_project",
      ["Uzun vadeli ortak bir proje için gerekenleri sırala:", ["Sabır", "İletişim", "Esneklik", "Disiplin"]],
      ["Rank what's needed for a long-term shared project:", ["Patience", "Communication", "Flexibility", "Discipline"]],
      ["Ordena lo necesario para un proyecto común a largo plazo:", ["Paciencia", "Comunicación", "Flexibilidad", "Disciplina"]]),
    ol("later_years_memories",
      ["Yaşlandığında anılarında en çok hatırlamak isteyeceğin şeyleri sırala:", ["Birlikte gülmeler", "Yaptığımız yolculuklar", "Zor zamanları aşmak", "Küçük günlük anlar"]],
      ["Rank what you'd most like to remember in your later years:", ["Laughing together", "The trips we took", "Getting through hard times", "Small everyday moments"]],
      ["Ordena lo que más te gustaría recordar en la vejez:", ["Reírnos juntos", "Los viajes que hicimos", "Superar los momentos difíciles", "Los pequeños momentos cotidianos"]]),
  ],
};
