import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Ev & Para — yalnızca "partner" (Hayat Arkadaşı). Ev düzeni, ortak harcama ve bütçe.
export const homeMoney: SeedCategory = {
  slug: "home_money",
  names: { tr: "Ev & Para", en: "Home & Money", es: "Casa y dinero" },
  relationshipTypes: ["partner"],
  isPremium: false,
  sortOrder: 6,
  questions: [
    sc("fair_chores",
      "Ev işlerini adil paylaşmak senin için çok önemli mi?",
      "Is sharing household chores fairly very important to you?",
      "¿Es muy importante para ti repartir las tareas del hogar de forma justa?"),
    sc("monthly_budget",
      "Aylık bir bütçe tutmak seni rahatlatır mı?",
      "Does keeping a monthly budget put you at ease?",
      "¿Llevar un presupuesto mensual te da tranquilidad?"),
    sc("second_opinion",
      "Büyük bir alışverişten önce mutlaka ikinci bir fikir alır mısın?",
      "Do you always get a second opinion before a big purchase?",
      "¿Siempre pides una segunda opinión antes de una compra grande?"),
    sc("spending_transparency",
      "Bütün harcamalarını birbirinizle şeffafça paylaşmak sana doğal gelir mi?",
      "Does sharing all your spending openly with each other feel natural to you?",
      "¿Te parece natural compartir con transparencia todos vuestros gastos?"),
    sc("saving_joy",
      "Para biriktirmek, harcamaktan daha çok keyif verir mi?",
      "Does saving money feel better than spending it?",
      "¿Ahorrar te da más satisfacción que gastar?"),
    sc("self_repair",
      "Evde bir şey bozulunca onu kendin onarmayı denersin?",
      "When something breaks at home, do you try to fix it yourself?",
      "Cuando algo se rompe en casa, ¿intentas arreglarlo tú mismo?"),
    sc("clear_house_rules",
      "Ev düzeni konusunda net kurallarımız olmasını tercih eder misin?",
      "Do you prefer having clear rules about how the home is run?",
      "¿Prefieres tener reglas claras sobre cómo se lleva la casa?"),
    sc("meal_planning",
      "Evde yemek planı ve alışveriş listesi hazırlamak sana iyi gelir mi?",
      "Does making a meal plan and shopping list work well for you?",
      "¿Te viene bien hacer un menú semanal y una lista de la compra?"),
    sc("diy_joy",
      "Bir tamir ya da dekorasyon projesini kendi başına yapmaktan keyif alır mısın?",
      "Do you enjoy doing a repair or decorating project yourself?",
      "¿Disfrutas haciendo tú mismo una reparación o un proyecto de decoración?"),
    sc("tracking_bills",
      "Aylık sabit giderleri (fatura, kira) düzenli takip etmek senin için kolay mı?",
      "Is tracking monthly fixed expenses (bills, rent) easy for you?",
      "¿Te resulta fácil llevar el control de los gastos fijos mensuales (facturas, alquiler)?"),

    pr("chore_style",
      ["Ev işleri birikti. Genelde ne yaparsın?",
        ["Hemen kalkıp hepsini hallederim", "Birlikte bir plan yapıp paylaşırız", "Haftalık bir takvimle yaparım", "Bir gün toplu olarak hallederim"]],
      ["Chores have piled up. What do you usually do?",
        ["Get up and do it all right away", "Make a plan together and split it", "Follow a weekly schedule", "Do it all in one go on a single day"]],
      ["Se han acumulado las tareas de casa. ¿Qué sueles hacer?",
        ["Me levanto y las hago todas enseguida", "Hacemos un plan juntos y las repartimos", "Sigo un calendario semanal", "Las hago todas de golpe un día"]]),
    pr("shared_savings",
      ["Ortak bir birikiminiz oluştu. Önceliğin ne olur?",
        ["Acil durum fonu olarak saklamak", "Eve ya da eşyaya yatırım yapmak", "Birlikte bir tatile çıkmak", "Borç ya da kredi ödemek"]],
      ["You've built up shared savings. What's your priority?",
        ["Keep it as an emergency fund", "Invest in the home or furnishings", "Take a vacation together", "Pay off debts or loans"]],
      ["Habéis reunido unos ahorros comunes. ¿Cuál es tu prioridad?",
        ["Guardarlo como fondo de emergencia", "Invertir en la casa o el mobiliario", "Irnos de vacaciones juntos", "Pagar deudas o préstamos"]]),
    pr("big_purchase",
      ["Pahalı bir eşya almayı düşünüyorsun. Nasıl karar verirsin?",
        ["Haftalarca araştırıp karşılaştırırım", "Beğendiysem hemen alırım", "Karşı tarafın da onayını mutlaka alırım", "İndirim ya da kampanya gelene kadar beklerim"]],
      ["You're thinking of buying something expensive. How do you decide?",
        ["Research and compare for weeks", "Buy it right away if I like it", "Always get the other person's approval", "Wait for a sale or promotion"]],
      ["Estás pensando en comprar algo caro. ¿Cómo decides?",
        ["Investigo y comparo durante semanas", "Lo compro enseguida si me gusta", "Siempre pido la aprobación de la otra persona", "Espero a una oferta o rebaja"]]),
    pr("cooking_roles",
      ["Yemek konusunda nasıl bir düzen istersin?",
        ["Dönüşümlü pişiririz", "Yemeği daha çok seven yapar, diğeri toparlar", "Sık sık dışarıdan söyleriz", "Hafta sonu toplu hazırlık yaparız"]],
      ["What kind of arrangement do you want for meals?",
        ["We take turns cooking", "Whoever enjoys cooking more cooks, the other cleans up", "We order in often", "We batch-prep on the weekend"]],
      ["¿Qué tipo de organización quieres para las comidas?",
        ["Nos turnamos para cocinar", "Cocina quien más lo disfruta y el otro recoge", "Pedimos comida a menudo", "Preparamos todo junto el fin de semana"]]),
    pr("money_disagreement",
      ["Para konusunda anlaşmazlık yaşadınız. Nasıl yaklaşırsın?",
        ["Rakamlarla, sakin ve net konuşurum", "Önce duygularımı anlatırım", "Üçüncü bir kişiden tavsiye alırız", "Konuyu kapatıp zamanla çözülmesini beklerim"]],
      ["You disagreed about money. How do you approach it?",
        ["Talk calmly and clearly with numbers", "Start by explaining how I feel", "Get advice from a third person", "Drop it and hope it resolves in time"]],
      ["Habéis discrepado sobre dinero. ¿Cómo lo abordas?",
        ["Hablo con calma y claridad, con números", "Empiezo explicando cómo me siento", "Pedimos consejo a una tercera persona", "Lo dejo y espero a que se resuelva con el tiempo"]]),
    pr("repair_style",
      ["Evde bir eşya bozuldu. Ne yaparsın?",
        ["Hemen kendim onarmaya çalışırım", "Bir usta çağırırım", "Karşı tarafın halletmesini beklerim", "Önce videolardan nasıl yapılacağını öğrenirim"]],
      ["Something broke at home. What do you do?",
        ["Try to fix it myself right away", "Call a repair person", "Wait for the other person to sort it", "Watch tutorials to learn how first"]],
      ["Se ha roto algo en casa. ¿Qué haces?",
        ["Intento arreglarlo yo enseguida", "Llamo a un técnico", "Espero a que lo resuelva la otra persona", "Primero veo tutoriales para aprender"]]),
    pr("spending_review",
      ["Aylık harcamalarınızı gözden geçirirken ne yaparsın?",
        ["Tablo hazırlayıp detaylı incelerim", "Büyük kalemlere göz atarım", "Birlikte sohbet ederek konuşuruz", "Çok bakmam, genel olarak yeterli sayarım"]],
      ["When reviewing your monthly spending, what do you do?",
        ["Build a spreadsheet and review in detail", "Look at the big items", "Chat about it together", "Don't look much, as long as it feels fine overall"]],
      ["Al revisar vuestros gastos mensuales, ¿qué haces?",
        ["Hago una hoja de cálculo y lo reviso al detalle", "Miro las partidas grandes", "Lo comentamos charlando juntos", "Miro poco, mientras todo parezca ir bien"]]),
    pr("budget_tension",
      ["Eve yeni bir eşya almak istiyorsun ama bütçe sınırlı. Ne yaparsın?",
        ["Birkaç ay biriktirip alırım", "Daha ucuz bir alternatif ararım", "Taksitle hemen alırım", "Gerçekten gerekip gerekmediğini konuşuruz"]],
      ["You want to buy something new for the home but the budget is tight. What do you do?",
        ["Save for a few months, then buy", "Look for a cheaper alternative", "Buy it now in installments", "Talk about whether we really need it"]],
      ["Quieres comprar algo nuevo para la casa pero el presupuesto es justo. ¿Qué haces?",
        ["Ahorro unos meses y lo compro", "Busco una alternativa más barata", "Lo compro ya a plazos", "Hablamos de si de verdad lo necesitamos"]]),
    pr("cleaning_plan",
      ["Hafta sonu ev temizliğini nasıl planlarsın?",
        ["Sabah erkenden hepsini bitiririm", "Gün içine yayarım", "Müzik açıp birlikte yaparız", "Mümkünse temizlik hizmeti alırız"]],
      ["How do you plan the weekend house cleaning?",
        ["Finish it all early in the morning", "Spread it through the day", "Put on music and do it together", "Hire a cleaning service if possible"]],
      ["¿Cómo planeas la limpieza de la casa del fin de semana?",
        ["La termino toda temprano por la mañana", "La reparto durante el día", "Ponemos música y la hacemos juntos", "Contratamos un servicio de limpieza si es posible"]]),
    pr("unexpected_expense",
      ["Beklenmedik bir ev masrafı çıktı. İlk tepkin ne olur?",
        ["Acil durum fonumuza başvururuz", "Önce gerçekten gerekli mi diye bakarım", "Farklı fiyat teklifleri toplarım", "Gerilir, endişelenirim"]],
      ["An unexpected household expense comes up. What's your first reaction?",
        ["Turn to our emergency fund", "First check whether it's truly necessary", "Collect several quotes", "Get stressed and worry"]],
      ["Surge un gasto imprevisto en casa. ¿Cuál es tu primera reacción?",
        ["Recurrimos a nuestro fondo de emergencia", "Primero compruebo si es realmente necesario", "Pido varios presupuestos", "Me estreso y me preocupo"]]),

    ol("money_priorities",
      ["Paranı en çok nelere ayırmak istersin? Sırala:", ["Birikim", "Ev ve yaşam alanı", "Seyahat ve eğlence", "Yeme içme"]],
      ["What would you most want to spend money on? Rank:", ["Savings", "Home and living space", "Travel and fun", "Food and drink"]],
      ["¿En qué querrías gastar más dinero? Ordena:", ["Ahorro", "Casa y espacio vital", "Viajes y ocio", "Comida y bebida"]]),
    ol("chores_dislike",
      ["Hangi ev işini yapmaktan en çok nefret edersin? En çok nefret ettiğinden başla:", ["Bulaşık", "Çamaşır ve ütü", "Banyo temizliği", "Çöp ve toparlanma"]],
      ["Which chore do you hate most? Start with the one you hate most:", ["Dishes", "Laundry and ironing", "Cleaning the bathroom", "Taking out the trash and tidying"]],
      ["¿Qué tarea del hogar odias más? Empieza por la que más odias:", ["Fregar los platos", "Lavar y planchar la ropa", "Limpiar el baño", "Sacar la basura y ordenar"]]),
    ol("home_atmosphere",
      ["Evde huzurlu hissetmek için önceliklerini sırala:", ["Düzen ve temizlik", "Sessizlik", "Güzel dekor ve ışık", "Misafir ağırlayabilmek"]],
      ["Rank your priorities for feeling at peace at home:", ["Order and cleanliness", "Quiet", "Nice decor and lighting", "Being able to host guests"]],
      ["Ordena tus prioridades para sentirte en paz en casa:", ["Orden y limpieza", "Silencio", "Buena decoración y luz", "Poder recibir invitados"]]),
    ol("financial_principles",
      ["Ortak para yönetiminde en önemli ilkeleri sırala:", ["Şeffaflık", "Adil paylaşım", "Ortak hedefler", "Kişisel harcama özgürlüğü"]],
      ["Rank the most important principles in managing money together:", ["Transparency", "Fair sharing", "Shared goals", "Freedom for personal spending"]],
      ["Ordena los principios más importantes al gestionar el dinero juntos:", ["Transparencia", "Reparto justo", "Objetivos comunes", "Libertad para gastos personales"]]),
    ol("budget_cuts",
      ["Ev bütçesinde kısmaya en yatkın olduğun kalemleri, ilk kısacağından başlayarak sırala:", ["Dışarıda yemek", "Eğlence", "Alışveriş", "Abonelikler"]],
      ["Rank the budget items you'd be most willing to cut, starting with the first to go:", ["Eating out", "Entertainment", "Shopping", "Subscriptions"]],
      ["Ordena las partidas del presupuesto que más fácilmente recortarías, empezando por la primera:", ["Comer fuera", "Ocio", "Compras", "Suscripciones"]]),
    ol("shared_living_rules",
      ["Ortak yaşam kurallarından en çok önem verdiklerini sırala:", ["Saygılı sessizlik saatleri", "Ortak alanların temizliği", "Misafir kuralları", "Eşyaların yerli yerinde olması"]],
      ["Rank the shared-living rules that matter most:", ["Respectful quiet hours", "Clean shared spaces", "Guest rules", "Things kept in their place"]],
      ["Ordena las reglas de convivencia que más importan:", ["Horas de silencio respetuosas", "Espacios comunes limpios", "Normas para invitados", "Cosas en su sitio"]]),
    ol("saving_methods",
      ["Birikim yapma yöntemlerini tercih sırasına göre sırala:", ["Otomatik aylık aktarım", "Hedefe yönelik hesap", "Yatırım", "Nakit saklamak"]],
      ["Rank your preferred ways to save money:", ["Automatic monthly transfers", "A goal-based account", "Investing", "Keeping cash"]],
      ["Ordena tus formas preferidas de ahorrar dinero:", ["Transferencias mensuales automáticas", "Una cuenta para un objetivo", "Invertir", "Guardar efectivo"]]),
    ol("enjoyed_chores",
      ["Ev işlerinde sana en çok keyif verenleri sırala:", ["Yemek yapmak", "Bahçe ya da bitki bakımı", "Düzen yapmak", "Küçük tamirler"]],
      ["Rank the chores you enjoy most:", ["Cooking", "Garden or plant care", "Organizing", "Small repairs"]],
      ["Ordena las tareas del hogar que más disfrutas:", ["Cocinar", "Cuidar el jardín o las plantas", "Ordenar", "Pequeñas reparaciones"]]),
    ol("home_shopping",
      ["Ev alışverişinde önceliklerini sırala:", ["Kalite", "Fiyat", "Çevre dostu olması", "Dayanıklılık"]],
      ["Rank your priorities when shopping for the home:", ["Quality", "Price", "Being eco-friendly", "Durability"]],
      ["Ordena tus prioridades al comprar para el hogar:", ["Calidad", "Precio", "Que sea ecológico", "Durabilidad"]]),
    ol("big_home_purchases",
      ["Ev için birlikte büyük harcama yapmayı düşündüğün kalemleri sırala:", ["Mobilya", "Beyaz eşya", "Dekorasyon", "Teknoloji"]],
      ["Rank the big items you'd consider spending on together for the home:", ["Furniture", "Appliances", "Decor", "Technology"]],
      ["Ordena las grandes partidas en las que gastaríais juntos para el hogar:", ["Muebles", "Electrodomésticos", "Decoración", "Tecnología"]]),
  ],
};
