import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Yaşam Tarzı — ortak (friend, dating, partner). Tür-bağımsız: ilişki/romantik çağrışım YOK.
export const lifestyle: SeedCategory = {
  slug: "lifestyle",
  names: { tr: "Yaşam Tarzı", en: "Lifestyle", es: "Estilo de vida" },
  relationshipTypes: ["friend", "dating", "partner"],
  isPremium: false,
  sortOrder: 9,
  questions: [
    sc("morning_person",
      "Sabah erken kalkmak sana enerji verir mi?",
      "Does waking up early give you energy?",
      "¿Madrugar te da energía?"),
    sc("tidiness",
      "Etrafın dağınıkken rahatça çalışabilir ya da dinlenebilir misin?",
      "Can you work or relax comfortably when your space is messy?",
      "¿Puedes trabajar o descansar a gusto con el espacio desordenado?"),
    sc("routine",
      "Her gün neredeyse aynı rutini sürdürmek seni huzurlu hissettirir mi?",
      "Does following nearly the same routine every day make you feel at peace?",
      "¿Seguir casi la misma rutina cada día te da tranquilidad?"),
    sc("digital_detox",
      "Telefonunu bir gün boyunca bir kenara bırakıp rahatça yaşayabilir misin?",
      "Could you leave your phone aside for a whole day and be fine?",
      "¿Podrías dejar el móvil de lado todo un día y estar tranquilo?"),
    sc("cooking_joy",
      "Yemek yapmaktan gerçekten keyif alır mısın?",
      "Do you genuinely enjoy cooking?",
      "¿Disfrutas de verdad cocinando?"),
    sc("exercise_habit",
      "Hava ne olursa olsun spora ya da yürüyüşe çıkma alışkanlığın var mı?",
      "Do you have a habit of exercising or walking no matter the weather?",
      "¿Tienes el hábito de hacer ejercicio o caminar sea cual sea el tiempo?"),
    sc("night_owl",
      "Gece geç saatlerde kendini en üretken ya da en canlı hisseder misin?",
      "Do you feel most productive or alive late at night?",
      "¿Te sientes más productivo o con más energía por la noche?"),
    sc("spontaneous_trips",
      "Plansız, aniden çıkılan bir yolculuğa hemen “evet” der misin?",
      "Would you say “yes” right away to an unplanned, last-minute trip?",
      "¿Dirías que sí enseguida a un viaje improvisado de última hora?"),

    pr("evening_style",
      ["Yorucu bir günün ardından akşamını nasıl geçirmek istersin?",
        ["Evde sessizce, tek başıma", "Birkaç yakınımla sohbet ederek", "Dışarı çıkıp hareketli bir şeyler yaparak", "Bir diziye ya da oyuna dalarak"]],
      ["After a tiring day, how would you like to spend your evening?",
        ["Quietly at home, on my own", "Chatting with a few close people", "Going out and doing something lively", "Diving into a series or a game"]],
      ["Tras un día agotador, ¿cómo te gustaría pasar la tarde?",
        ["En casa, tranquilo y a solas", "Charlando con unas pocas personas cercanas", "Saliendo a hacer algo animado", "Sumergido en una serie o un juego"]]),
    pr("food_choice",
      ["Bir restoranda menüyü açtın. Genelde ne yaparsın?",
        ["Hep sevdiğim bildik şeyi söylerim", "Menüde daha önce yemediğim bir şey seçerim", "Garsona ya da yanımdakilere sorup karar veririm", "Çok uzun düşünür, en son aceleyle seçerim"]],
      ["You've just opened a restaurant menu. What do you usually do?",
        ["Order my usual favorite", "Pick something I've never tried", "Ask the waiter or others and decide", "Think for ages and choose in a rush at the end"]],
      ["Acabas de abrir la carta de un restaurante. ¿Qué sueles hacer?",
        ["Pido lo de siempre", "Elijo algo que nunca he probado", "Pregunto al camarero o a los demás y decido", "Dudo muchísimo y elijo con prisas al final"]]),
    pr("free_day",
      ["Tüm gününün tamamen boş olduğunu öğrendin. İlk ne yaparsın?",
        ["Uzun uzun uyurum", "Hemen bir plan yapıp dışarı çıkarım", "Ertelediğim işleri halledip rahatlarım", "Hiçbir şey yapmadan akışa bırakırım"]],
      ["You find out your whole day is completely free. What's the first thing you do?",
        ["Sleep in for ages", "Make a plan and head out right away", "Take care of the tasks I've been putting off", "Do nothing and go with the flow"]],
      ["Descubres que tienes el día entero libre. ¿Qué haces primero?",
        ["Dormir hasta tarde", "Hacer un plan y salir enseguida", "Resolver las tareas que había aplazado", "No hacer nada y dejarme llevar"]]),
    pr("guests_coming",
      ["Misafir geleceğini 10 dakika önce öğrendin. Evinde ne yaparsın?",
        ["Koşturup her yeri toplarım", "Sadece göze çarpanları düzeltirim", "Olduğu gibi bırakırım, kimse yargılamaz", "Dışarıda görüşmeyi öneririm"]],
      ["You find out guests are coming in 10 minutes. What do you do at home?",
        ["Rush around and tidy everything", "Fix only what's visible", "Leave it as it is, nobody will judge", "Suggest meeting somewhere outside instead"]],
      ["Te enteras de que llegan invitados en 10 minutos. ¿Qué haces en casa?",
        ["Corro a ordenarlo todo", "Arreglo solo lo que se ve", "Lo dejo como está, nadie va a juzgar", "Propongo vernos fuera"]]),
    pr("holiday_style",
      ["Hayalindeki tatil hangisine daha yakın?",
        ["Plajda tamamen dinlenmek", "Yeni bir şehirde gezip keşfetmek", "Doğada kamp ya da yürüyüş", "Yerel yemekler ve festivaller peşinde koşmak"]],
      ["Which is closest to your dream vacation?",
        ["Total relaxation on a beach", "Exploring a new city", "Camping or hiking in nature", "Chasing local food and festivals"]],
      ["¿Cuál se parece más a tus vacaciones soñadas?",
        ["Descanso total en la playa", "Explorar una ciudad nueva", "Acampar o hacer senderismo en la naturaleza", "Buscar comida local y festivales"]]),

    ol("morning_priorities",
      ["Güne iyi başlamak için olmazsa olmazlarını sırala:", ["Kahve ya da çay", "Sakin ve acelesiz bir sabah", "Kısa bir hareket ya da spor", "İyi bir kahvaltı"]],
      ["Rank your must-haves for a good start to the day:", ["Coffee or tea", "A calm, unhurried morning", "A bit of movement or exercise", "A good breakfast"]],
      ["Ordena tus imprescindibles para empezar bien el día:", ["Café o té", "Una mañana tranquila y sin prisas", "Algo de movimiento o ejercicio", "Un buen desayuno"]]),
    ol("free_time_spend",
      ["Boş zamanını nasıl değerlendirdiğini, en çok yaptığından başlayarak sırala:", ["Ekran karşısında (dizi, oyun)", "Okumak ya da yeni bir şey öğrenmek", "Dışarıda gezmek ya da spor", "Yemek yapmak ya da bir şeyler üretmek"]],
      ["Rank how you spend free time, starting with what you do most:", ["Screens (series, games)", "Reading or learning something new", "Being outdoors or exercising", "Cooking or making things"]],
      ["Ordena cómo usas tu tiempo libre, empezando por lo que más haces:", ["Pantallas (series, juegos)", "Leer o aprender algo nuevo", "Estar al aire libre o hacer deporte", "Cocinar o crear cosas"]]),
    ol("spending_priorities",
      ["Parayı en çok neye harcamaktan keyif alırsın? Sırala:", ["Yeme içme", "Seyahat", "Teknoloji ve eşyalar", "Deneyimler (konser, kurs vb.)"]],
      ["What do you enjoy spending money on most? Rank:", ["Food and drink", "Travel", "Tech and gadgets", "Experiences (concerts, classes)"]],
      ["¿En qué te gusta más gastar dinero? Ordena:", ["Comer y beber", "Viajes", "Tecnología y objetos", "Experiencias (conciertos, cursos)"]]),
    ol("home_must_haves",
      ["Yaşadığın mekânda olmazsa olmazlarını sırala:", ["Kaliteli uyku düzeni", "Düzen ve temizlik", "Güzel bir ışık ve atmosfer", "Hızlı internet"]],
      ["Rank your must-haves in the place you live:", ["Quality sleep", "Order and cleanliness", "Nice lighting and atmosphere", "Fast internet"]],
      ["Ordena tus imprescindibles en el lugar donde vives:", ["Buen descanso", "Orden y limpieza", "Buena luz y ambiente", "Internet rápido"]]),

    // ── Tamamlama: her modda 10'a ──────────────────────────────────────
    sc("hobby_exploration",
      "Sık sık yeni hobiler denemeyi sever misin?",
      "Do you like trying new hobbies often?",
      "¿Te gusta probar aficiones nuevas con frecuencia?"),
    sc("homebody",
      "Bir hafta sonunu tamamen evde geçirmek seni sıkar mı?",
      "Does spending a whole weekend at home bore you?",
      "¿Te aburre pasar un fin de semana entero en casa?"),

    pr("alarm_style",
      ["Sabah alarmın çaldı. Ne yaparsın?",
        ["Hemen kalkarım", "Birkaç kez erteler, sonra kalkarım", "Alarmı kapatıp uyumaya devam ederim", "Alarm çalmadan kendiliğimden uyanırım"]],
      ["Your morning alarm goes off. What do you do?",
        ["Get up immediately", "Snooze a few times, then get up", "Switch it off and keep sleeping", "I wake up before it rings"]],
      ["Suena tu alarma por la mañana. ¿Qué haces?",
        ["Me levanto enseguida", "La pospongo varias veces y luego me levanto", "La apago y sigo durmiendo", "Me despierto antes de que suene"]]),
    pr("weather_plans",
      ["Hafta sonu için hava çok güzel. Ne yaparsın?",
        ["Doğaya ya da parka giderim", "Arkadaşlarla bir etkinlik ayarlarım", "Evde kalıp yarım kalan işleri bitiririm", "Pencereleri açıp evde keyif yaparım"]],
      ["The weather's perfect this weekend. What do you do?",
        ["Head to nature or a park", "Set up something with friends", "Stay in and finish pending tasks", "Open the windows and enjoy staying in"]],
      ["Hace un tiempo perfecto este fin de semana. ¿Qué haces?",
        ["Voy a la naturaleza o a un parque", "Organizo algo con amigos", "Me quedo en casa a terminar tareas pendientes", "Abro las ventanas y disfruto en casa"]]),
    pr("phone_battery",
      ["Telefonunun şarjı bitmek üzere ve yanında şarj aleti yok. Ne yaparsın?",
        ["Panik yapıp hemen şarj ararım", "Gereksiz uygulamaları kapatıp idare ederim", "Rahat kalırım, birkaç saat telefonsuz olur", "Birinden şarj aleti isterim"]],
      ["Your phone is about to die and you have no charger. What do you do?",
        ["Panic and look for a charger right away", "Close unnecessary apps and make do", "Stay calm, a few hours without a phone is fine", "Ask someone to borrow a charger"]],
      ["Tu móvil está a punto de apagarse y no tienes cargador. ¿Qué haces?",
        ["Entro en pánico y busco un cargador enseguida", "Cierro apps innecesarias y me las apaño", "Me relajo, unas horas sin móvil no pasa nada", "Le pido un cargador a alguien"]]),
    pr("habit_building",
      ["Yeni bir alışkanlık edinmek istiyorsun (örneğin spor). Nasıl başlarsın?",
        ["Detaylı bir program yapıp başlarım", "Küçük adımlarla, yavaş yavaş", "Biriyle birlikte, sorumluluk için", "Ruh halim yerindeyken yaparım"]],
      ["You want to build a new habit (like exercise). How do you start?",
        ["Make a detailed schedule and begin", "In small steps, gradually", "With someone else for accountability", "Whenever I feel in the mood"]],
      ["Quieres adquirir un hábito nuevo (como hacer ejercicio). ¿Cómo empiezas?",
        ["Hago un programa detallado y empiezo", "Con pequeños pasos, poco a poco", "Con alguien más, para tener compromiso", "Cuando me apetece"]]),
    pr("cooking_style",
      ["Mutfakta bir şeyler hazırlıyorsun ve elinde tarif yok. Ne yaparsın?",
        ["Elimdekilerle doğaçlama yaparım", "Hemen tarif arar, adım adım uygularım", "Basit bir şey yapıp geçerim", "Dışarıdan sipariş veririm"]],
      ["You're cooking and there's no recipe. What do you do?",
        ["Improvise with what I have", "Look up a recipe and follow it step by step", "Make something simple and be done", "Order in instead"]],
      ["Estás cocinando y no tienes receta. ¿Qué haces?",
        ["Improviso con lo que tengo", "Busco una receta y la sigo paso a paso", "Hago algo sencillo y listo", "Pido comida a domicilio"]]),

    ol("favorite_time_of_day",
      ["Günün hangi saatlerini en çok seversin? En sevdiğinden başla:", ["Sabah", "Öğleden sonra", "Akşam", "Gece geç saatler"]],
      ["Rank the times of day you enjoy most, starting with your favorite:", ["Morning", "Afternoon", "Evening", "Late night"]],
      ["Ordena los momentos del día que más disfrutas, empezando por tu favorito:", ["Mañana", "Tarde", "Noche", "Madrugada"]]),
    ol("relaxation_sources",
      ["Seni en çok rahatlatan şeyleri sırala:", ["Müzik dinlemek", "Doğada vakit geçirmek", "Sıcak bir duş", "İyi bir yemek"]],
      ["Rank what relaxes you most:", ["Listening to music", "Spending time in nature", "A hot shower", "A good meal"]],
      ["Ordena lo que más te relaja:", ["Escuchar música", "Pasar tiempo en la naturaleza", "Una ducha caliente", "Una buena comida"]]),
    ol("city_priorities",
      ["Yaşayacağın bir şehirde en önemli özellikleri sırala:", ["Ulaşım kolaylığı", "Yeşil alanlar", "Sosyal hayat", "Sakinlik"]],
      ["Rank the most important features of a city to live in:", ["Easy transportation", "Green spaces", "Social life", "Peace and quiet"]],
      ["Ordena las características más importantes de una ciudad para vivir:", ["Transporte fácil", "Zonas verdes", "Vida social", "Tranquilidad"]]),
    ol("shopping_priorities",
      ["Alışveriş yaparken neye en çok dikkat edersin? Sırala:", ["Fiyat", "Kalite", "Tasarım", "Marka ve güvenilirlik"]],
      ["When shopping, what do you pay most attention to? Rank:", ["Price", "Quality", "Design", "Brand and reliability"]],
      ["Al comprar, ¿a qué prestas más atención? Ordena:", ["Precio", "Calidad", "Diseño", "Marca y fiabilidad"]]),
    ol("indispensable_habits",
      ["Bir hafta boyunca vazgeçemeyeceğin alışkanlıkları sırala:", ["Kahve ya da çay", "Müzik", "Telefon", "Düzenli yürüyüş"]],
      ["Rank the habits you couldn't give up for a week:", ["Coffee or tea", "Music", "My phone", "A regular walk"]],
      ["Ordena los hábitos a los que no podrías renunciar durante una semana:", ["Café o té", "Música", "Mi móvil", "Un paseo regular"]]),
    ol("new_country_priorities",
      ["Yeni bir ülkede ilk yapmak isteyeceğin şeyleri sırala:", ["Yerel yemekleri denemek", "Tarihi yerleri gezmek", "Sokaklarda yürüyüp keşfetmek", "Yerel insanlarla sohbet etmek"]],
      ["Rank what you'd want to do first in a new country:", ["Try local food", "Visit historical sites", "Wander and explore the streets", "Chat with locals"]],
      ["Ordena lo que querrías hacer primero en un país nuevo:", ["Probar la comida local", "Visitar lugares históricos", "Pasear y explorar las calles", "Charlar con la gente local"]]),
  ],
};
