import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Romantizm — yalnızca "dating". Sevgi dilleri, jestler, bağlılık; sıcak ve açık/müstehcen olmayan bir dil.
export const romance: SeedCategory = {
  slug: "romance",
  names: { tr: "Romantizm", en: "Romance", es: "Romance" },
  relationshipTypes: ["dating"],
  isPremium: false,
  sortOrder: 4,
  questions: [
    sc("small_surprises",
      "Sevdiğin birine küçük sürprizler yapmayı sever misin?",
      "Do you like surprising someone you love with little things?",
      "¿Te gusta darle pequeñas sorpresas a alguien a quien quieres?"),
    sc("words_vs_actions",
      "Sevgini sözle ifade etmek, davranışla göstermekten daha kolay mı?",
      "Is expressing love in words easier for you than showing it through actions?",
      "¿Te resulta más fácil expresar el cariño con palabras que con hechos?"),
    sc("special_days",
      "Yıl dönümü ve özel günleri unutmamak senin için önemli mi?",
      "Is remembering anniversaries and special days important to you?",
      "¿Es importante para ti no olvidar los aniversarios y días especiales?"),
    sc("strong_bond_apart",
      "Birbirinizle her gün konuşmasanız da bağınızın güçlü kalabileceğine inanır mısın?",
      "Do you believe your bond can stay strong even if you don't talk every day?",
      "¿Crees que vuestro vínculo puede seguir siendo fuerte aunque no habléis todos los días?"),
    sc("physical_closeness",
      "Sevgini göstermek için fiziksel yakınlık (sarılma, el tutma) senin için çok önemli mi?",
      "Is physical closeness (hugs, holding hands) very important to you when showing affection?",
      "¿Es muy importante para ti la cercanía física (abrazos, ir de la mano) al mostrar cariño?"),
    sc("being_yourself",
      "Sevdiğin birinin yanında tamamen kendin olabildiğini hisseder misin?",
      "Do you feel you can be completely yourself around someone you love?",
      "¿Sientes que puedes ser totalmente tú mismo con alguien a quien quieres?"),
    sc("carrying_hurt",
      "Küçük bir kırgınlığı hemen konuşmak yerine bir süre içinde taşır mısın?",
      "Do you tend to carry a small hurt for a while instead of talking about it right away?",
      "¿Sueles guardar un pequeño disgusto un tiempo en lugar de hablarlo enseguida?"),
    sc("old_photos",
      "Birlikte eski fotoğraflara bakıp anıları hatırlamak seni mutlu eder mi?",
      "Does looking at old photos together and remembering make you happy?",
      "¿Te hace feliz mirar fotos antiguas juntos y recordar?"),
    sc("meaningful_gifts",
      "Bir hediye seçerken fiyatından çok anlamına önem verir misin?",
      "When choosing a gift, do you care more about its meaning than its price?",
      "Al elegir un regalo, ¿te importa más su significado que su precio?"),
    sc("cheering_up",
      "Sevdiğin birinin günü kötü geçtiğinde, ona özel bir şey yaparak moral vermeyi dener misin?",
      "When someone you love has a bad day, do you try to cheer them up with something special?",
      "Cuando alguien a quien quieres tiene un mal día, ¿intentas animarle con algo especial?"),

    pr("love_language",
      ["Sevildiğini en çok hangi şekilde hissedersin?",
        ["Güzel sözler duyunca", "Birlikte kaliteli zaman geçirince", "Düşünceli bir hediye alınca", "Biri bir işimi üstlenip yardımcı olunca"]],
      ["In which way do you feel most loved?",
        ["Hearing kind words", "Spending quality time together", "Receiving a thoughtful gift", "When someone takes a task off my plate"]],
      ["¿De qué manera te sientes más querido?",
        ["Al oír palabras bonitas", "Pasando tiempo de calidad juntos", "Recibiendo un regalo con detalle", "Cuando alguien me ayuda con una tarea"]]),
    pr("anniversary_style",
      ["Yıl dönümünüzü nasıl kutlamak istersin?",
        ["Sürpriz bir akşam yemeği", "Evde sakin bir akşam", "Küçük bir kaçamak", "Sade ve samimi bir kutlama"]],
      ["How would you like to celebrate your anniversary?",
        ["A surprise dinner", "A quiet evening at home", "A little getaway", "Something simple and heartfelt"]],
      ["¿Cómo te gustaría celebrar vuestro aniversario?",
        ["Una cena sorpresa", "Una noche tranquila en casa", "Una pequeña escapada", "Algo sencillo y sincero"]]),
    pr("making_up",
      ["Sevgilinle küçük bir tartışma yaşadınız. Barışmak için ne yaparsın?",
        ["İlk adımı atar, konuşurum", "Küçük bir jest yaparım (yemek, not)", "Biraz zaman tanırım, kendiliğinden geçer", "Karşı tarafın gelmesini beklerim"]],
      ["You and your partner had a small argument. How do you make up?",
        ["Take the first step and talk", "Make a small gesture (a meal, a note)", "Give it time, it passes", "Wait for them to come to me"]],
      ["Has tenido una pequeña discusión con tu pareja. ¿Cómo hacéis las paces?",
        ["Doy el primer paso y hablo", "Hago un pequeño gesto (una comida, una nota)", "Dejo pasar un poco de tiempo", "Espero a que venga la otra persona"]]),
    pr("public_affection",
      ["Başkalarının yanında sevgini göstermek konusunda nasılsın?",
        ["Rahatım, el tutar, sarılırım", "Sadece küçük jestler yaparım", "Daha çok baş başayken gösteririm", "Genelde çekinirim"]],
      ["How are you with showing affection in front of others?",
        ["Comfortable, holding hands and hugging", "Only small gestures", "I show it mostly when it's just the two of us", "I usually feel shy"]],
      ["¿Cómo llevas mostrar cariño delante de los demás?",
        ["Cómodo, voy de la mano y abrazo", "Solo pequeños gestos", "Lo muestro sobre todo cuando estamos solos", "Suelo cortarme"]]),
    pr("surprise_gift",
      ["Sevgiline sürpriz bir hediye alacaksın. Nasıl bir şey seçersin?",
        ["Çok düşündüğüm, anlamlı ve kişisel bir şey", "Uzun zamandır istediği bir şey", "Birlikte yaşayabileceğimiz bir deneyim", "Küçük ama sık sık verilen hediyeler"]],
      ["You're picking a surprise gift for your partner. What do you choose?",
        ["Something meaningful and personal", "Something they've wanted for a long time", "An experience we can share", "Small but frequent gifts"]],
      ["Vas a elegir un regalo sorpresa para tu pareja. ¿Qué eliges?",
        ["Algo con significado y personal", "Algo que lleva tiempo queriendo", "Una experiencia que podamos compartir", "Regalos pequeños pero frecuentes"]]),
    pr("weekend_together",
      ["Sevdiğin biriyle hafta sonu planı yapıyorsun. Tercihin ne olur?",
        ["Macera dolu bir şeyler", "Evde sakin bir gün", "Güzel bir yemek ve sohbet", "Doğada uzun bir yürüyüş"]],
      ["You're planning a weekend with someone you love. What do you prefer?",
        ["Something adventurous", "A calm day at home", "A nice meal and conversation", "A long walk in nature"]],
      ["Estás planeando un fin de semana con alguien a quien quieres. ¿Qué prefieres?",
        ["Algo aventurero", "Un día tranquilo en casa", "Una buena comida y conversación", "Un largo paseo por la naturaleza"]]),
    pr("partner_tired",
      ["Sevgilin bir gün çok yorgun eve geldi. Ne yaparsın?",
        ["Ona sarılıp dinlenmesine yardım ederim", "Yemek hazırlar, ona bakarım", "Sormadan yanında oturur, dinlemeye hazır olurum", "Biraz yalnız kalmasına izin veririm"]],
      ["Your partner comes home exhausted. What do you do?",
        ["Hug them and help them rest", "Make dinner and take care of them", "Sit with them without asking, ready to listen", "Give them some time alone"]],
      ["Tu pareja llega a casa agotada. ¿Qué haces?",
        ["La abrazo y la ayudo a descansar", "Preparo la cena y la cuido", "Me siento a su lado sin preguntar, listo para escuchar", "Le dejo un rato a solas"]]),
    pr("memory_lane",
      ["Birlikte bir yıl dönümü fotoğrafına bakıyorsunuz. Ne yaparsın?",
        ["Anıları tek tek anlatırım", "Gülüp o günkü şakaları hatırlarım", "Duygulanıp sarılırım", "Yeni bir fotoğraf çekmeyi öneririm"]],
      ["You're looking at an anniversary photo together. What do you do?",
        ["Recount the memories one by one", "Laugh and recall the jokes from that day", "Get emotional and hug", "Suggest taking a new photo"]],
      ["Miráis juntos una foto de aniversario. ¿Qué haces?",
        ["Voy contando los recuerdos uno por uno", "Me río recordando las bromas de ese día", "Me emociono y la abrazo", "Propongo hacernos una foto nueva"]]),
    pr("shared_dream",
      ["Sevgilinle ortak bir hayal kurarken hangisini seçersin?",
        ["Birlikte uzak bir ülkeye taşınmak", "Küçük, sevimli bir ev", "Dünya turu", "Birlikte bir iş kurmak"]],
      ["While dreaming together with your partner, which do you pick?",
        ["Moving to a far-off country together", "A small, cozy home", "A trip around the world", "Starting a business together"]],
      ["Al soñar juntos con tu pareja, ¿cuál eliges?",
        ["Mudarnos juntos a un país lejano", "Una casita acogedora", "Dar la vuelta al mundo", "Montar un negocio juntos"]]),
    pr("forgot_special_day",
      ["Özel bir günü unuttuğunu fark ettin. Ne yaparsın?",
        ["Hemen açıkça söyler, özür dilerim", "Telafi için büyük bir sürpriz hazırlarım", "Küçük bir jestle durumu toparlarım", "Hiçbir şey olmamış gibi davranırım"]],
      ["You realize you forgot a special day. What do you do?",
        ["Tell them right away and apologize", "Prepare a big surprise to make up for it", "Smooth it over with a small gesture", "Act as if nothing happened"]],
      ["Te das cuenta de que olvidaste un día especial. ¿Qué haces?",
        ["Se lo digo enseguida y me disculpo", "Preparo una gran sorpresa para compensarlo", "Lo arreglo con un pequeño gesto", "Hago como si nada"]]),

    ol("affection_expressions",
      ["Sevgini göstermek için en çok yaptığın şeyleri sırala:", ["Sözlü ifade (iltifat, “seni seviyorum”)", "Fiziksel yakınlık", "Birlikte vakit geçirmek", "Hediye ya da jestler"]],
      ["Rank what you most do to show affection:", ["Words (compliments, “I love you”)", "Physical closeness", "Spending time together", "Gifts or gestures"]],
      ["Ordena lo que más haces para mostrar cariño:", ["Palabras (cumplidos, «te quiero»)", "Cercanía física", "Pasar tiempo juntos", "Regalos o detalles"]]),
    ol("romantic_evening",
      ["Romantik bir akşam için öncelik sırasını belirle:", ["Mum ışığında yemek", "Birlikte film", "Sahilde yürüyüş", "Evde birlikte yemek yapmak"]],
      ["Rank your priorities for a romantic evening:", ["A candlelit dinner", "A movie together", "A walk by the sea", "Cooking at home together"]],
      ["Ordena tus prioridades para una velada romántica:", ["Cena a la luz de las velas", "Una película juntos", "Un paseo junto al mar", "Cocinar juntos en casa"]]),
    ol("needs_from_loved_one",
      ["Sevdiğin kişiden en çok neye ihtiyaç duyarsın? Sırala:", ["Anlaşıldığımı hissetmek", "Destek görmek", "Takdir edilmek", "Kendime alan tanınması"]],
      ["What do you need most from the person you love? Rank:", ["Feeling understood", "Feeling supported", "Feeling appreciated", "Being given space"]],
      ["¿Qué necesitas más de la persona que quieres? Ordena:", ["Sentirme comprendido", "Sentirme apoyado", "Sentirme valorado", "Que me den espacio"]]),
    ol("trust_in_love",
      ["Güven duygusunu en çok besleyen şeyleri sırala:", ["Dürüst olmak", "Tutarlı davranmak", "Zor zamanda yanında durmak", "Sır saklamak"]],
      ["Rank what nurtures trust the most:", ["Being honest", "Being consistent", "Standing by each other in hard times", "Keeping secrets"]],
      ["Ordena lo que más alimenta la confianza:", ["Ser honesto", "Ser constante", "Estar al lado en los momentos difíciles", "Guardar secretos"]]),
    ol("little_joys",
      ["Sevgi dolu bir bağda seni en çok mutlu eden küçük şeyleri sırala:", ["Günaydın mesajı", "Sürpriz bir not", "Birlikte yemek yemek", "Bir sarılma"]],
      ["Rank the little things in a loving bond that make you happiest:", ["A good-morning text", "A surprise note", "Eating together", "A hug"]],
      ["Ordena las pequeñas cosas de un vínculo cariñoso que más te hacen feliz:", ["Un mensaje de buenos días", "Una nota sorpresa", "Comer juntos", "Un abrazo"]]),
    ol("romantic_activities",
      ["Birlikte yapılacak romantik aktiviteleri sırala:", ["Gün batımını izlemek", "Birlikte yemek yapmak", "Yıldızların altında yürümek", "Müzik dinleyip dans etmek"]],
      ["Rank romantic activities to do together:", ["Watching the sunset", "Cooking together", "Walking under the stars", "Listening to music and dancing"]],
      ["Ordena las actividades románticas para hacer juntos:", ["Ver la puesta de sol", "Cocinar juntos", "Pasear bajo las estrellas", "Escuchar música y bailar"]]),
    ol("valued_love_forms",
      ["Sevgi gösterme biçimlerinden en değerli bulduklarını sırala:", ["Sözler", "Dokunuş", "Zaman ayırmak", "Hediyeler"]],
      ["Rank the ways of showing love you find most valuable:", ["Words", "Touch", "Giving time", "Gifts"]],
      ["Ordena las formas de mostrar amor que te parecen más valiosas:", ["Palabras", "Contacto físico", "Dedicar tiempo", "Regalos"]]),
    ol("surprise_impressions",
      ["Bir sürprizde seni en çok etkileyen şeyleri sırala:", ["Düşünceli olması", "Hazırlığa emek verilmiş olması", "Beklenmedik olması", "Anlamlı bir detay içermesi"]],
      ["Rank what impresses you most about a surprise:", ["Being thoughtful", "The effort put into it", "Being unexpected", "Including a meaningful detail"]],
      ["Ordena lo que más te impresiona de una sorpresa:", ["Que sea considerada", "El esfuerzo invertido", "Que sea inesperada", "Que incluya un detalle significativo"]]),
    ol("lasting_foundations",
      ["Uzun ömürlü bir bağın temellerini sırala:", ["Güven", "Saygı", "Ortak hedefler", "Birlikte gülebilmek"]],
      ["Rank the foundations of a long-lasting bond:", ["Trust", "Respect", "Shared goals", "Being able to laugh together"]],
      ["Ordena los cimientos de un vínculo duradero:", ["Confianza", "Respeto", "Metas compartidas", "Poder reírnos juntos"]]),
    ol("ideal_day",
      ["Sevdiğinle geçireceğin ideal bir günün parçalarını sırala:", ["Güzel bir kahvaltı", "Küçük bir gezi", "Birlikte film", "Akşam yürüyüşü"]],
      ["Rank the parts of an ideal day with someone you love:", ["A lovely breakfast", "A short outing", "A movie together", "An evening walk"]],
      ["Ordena las partes de un día ideal con alguien a quien quieres:", ["Un buen desayuno", "Una pequeña excursión", "Una película juntos", "Un paseo por la tarde"]]),
  ],
};
