import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Sosyal Hayat — yalnızca "friend". Romantik çağrışım YOK (denetlenir).
export const socialLife: SeedCategory = {
  slug: "social_life",
  names: { tr: "Sosyal Hayat", en: "Social Life", es: "Vida social" },
  relationshipTypes: ["friend"],
  isPremium: false,
  sortOrder: 7,
  questions: [
    sc("hosting",
      "Evinde arkadaşlarını ağırlamaktan keyif alır mısın?",
      "Do you enjoy hosting friends at your place?",
      "¿Disfrutas recibiendo a tus amigos en casa?"),
    sc("cancelling_plans",
      "Çok yorgunsan, daha önce kabul ettiğin bir planı iptal etmeyi düşünür müsün?",
      "If you're very tired, would you consider cancelling a plan you already agreed to?",
      "Si estás muy cansado, ¿te plantearías cancelar un plan que ya habías aceptado?"),
    sc("meeting_new_people",
      "Yeni insanlarla tanışmak seni heyecanlandırır mı?",
      "Does meeting new people excite you?",
      "¿Conocer gente nueva te emociona?"),
    sc("small_group",
      "Kalabalık bir ortamdan çok, küçük bir grupla vakit geçirmeyi mi tercih edersin?",
      "Do you prefer spending time in a small group over a big crowd?",
      "¿Prefieres pasar tiempo con un grupo pequeño antes que con una multitud?"),
    sc("friends_posts",
      "Arkadaşlarının paylaşımlarını düzenli takip eder ve beğenir misin?",
      "Do you regularly follow and like your friends' posts?",
      "¿Sigues y das me gusta con regularidad a las publicaciones de tus amigos?"),
    sc("birthdays",
      "Arkadaşlarının doğum günlerini aklında tutar ve mutlaka kutlar mısın?",
      "Do you remember your friends' birthdays and always celebrate them?",
      "¿Recuerdas los cumpleaños de tus amigos y siempre los felicitas?"),
    sc("mediating",
      "İki arkadaşının arasında bir gerginlik olursa arabulucu olmaya çalışır mısın?",
      "If tension arises between two of your friends, do you try to mediate?",
      "Si surge tensión entre dos de tus amigos, ¿intentas mediar?"),
    sc("alone_time",
      "Arkadaşlarınla çok vakit geçirsen bile tek başına kalmaya ihtiyaç duyar mısın?",
      "Even when you spend lots of time with friends, do you need time alone?",
      "Aunque pases mucho tiempo con amigos, ¿necesitas tiempo a solas?"),
    sc("friends_of_friends",
      "Bir arkadaşın seni yeni biriyle tanıştırdığında hemen kaynaşabilir misin?",
      "When a friend introduces you to someone new, can you hit it off quickly?",
      "Cuando un amigo te presenta a alguien nuevo, ¿conectas rápido?"),
    sc("long_gap_friendship",
      "Bir arkadaşınla aylarca konuşmasanız bile, tekrar görüştüğünüzde kaldığınız yerden devam edebilir misiniz?",
      "If you haven't spoken to a friend for months, can you pick up right where you left off?",
      "Si llevas meses sin hablar con un amigo, ¿podéis retomarlo donde lo dejasteis?"),

    pr("party_role",
      ["Bir arkadaşın doğum günü partisinde genelde ne yaparsın?",
        ["Ortamı hareketlendirir, herkesle konuşurum", "Tanıdığım birkaç kişiyle köşede sohbet ederim", "Organizasyona yardım eder, bir şeylerle ilgilenirim", "Erken ayrılmak için fırsat kollarım"]],
      ["At a friend's birthday party, what do you usually do?",
        ["Liven things up and talk to everyone", "Chat in a corner with the few people I know", "Help with the organizing and keep busy", "Look for a chance to leave early"]],
      ["En la fiesta de cumpleaños de un amigo, ¿qué sueles hacer?",
        ["Animo el ambiente y hablo con todos", "Charlo en un rincón con los pocos que conozco", "Ayudo con la organización y me ocupo de cosas", "Busco la ocasión de irme pronto"]]),
    pr("new_group",
      ["Yeni bir arkadaş grubuna dahil oldun. İlk haftalarda nasıl davranırsın?",
        ["Hemen kaynaşır, espri yaparım", "Önce herkesi gözlemlerim", "Bir iki kişiyle yakınlaşırım", "Mesafeli dururum, zamanla açılırım"]],
      ["You've joined a new friend group. How do you act in the first weeks?",
        ["Blend in right away and joke around", "Observe everyone first", "Get close to one or two people", "Stay reserved and open up over time"]],
      ["Te has unido a un grupo de amigos nuevo. ¿Cómo te comportas las primeras semanas?",
        ["Me integro enseguida y bromeo", "Observo a todos primero", "Me acerco a una o dos personas", "Soy reservado y me voy abriendo con el tiempo"]]),
    pr("lending_money",
      ["Bir arkadaşın senden borç para istedi. Ne yaparsın?",
        ["Sorgulamadan veririm", "Neden istediğini sorup karar veririm", "İmkânıma göre küçük bir miktar veririm", "Genelde nazikçe reddederim"]],
      ["A friend asks to borrow money from you. What do you do?",
        ["Lend it without questions", "Ask why and then decide", "Lend a small amount within my means", "Usually politely decline"]],
      ["Un amigo te pide dinero prestado. ¿Qué haces?",
        ["Se lo presto sin preguntar", "Pregunto para qué y decido", "Presto una cantidad pequeña según mis posibilidades", "Normalmente lo rechazo con educación"]]),
    pr("group_decision",
      ["Grup akşam ne yiyeceğine karar veremiyor. Sen ne yaparsın?",
        ["Hemen bir yer önerip kararı bağlarım", "Herkesin fikrini sorup ortak nokta bulurum", "Hangi karar olursa uyarım", "Sıkılıp “ben eve gidiyorum” derim"]],
      ["The group can't decide where to eat. What do you do?",
        ["Suggest a place right away and settle it", "Ask everyone and find common ground", "Go along with whatever's decided", "Get fed up and say “I'm going home”"]],
      ["El grupo no se pone de acuerdo sobre dónde cenar. ¿Qué haces?",
        ["Propongo un sitio enseguida y cierro el tema", "Pregunto a todos y busco un punto en común", "Me adapto a lo que se decida", "Me harto y digo «me voy a casa»"]]),
    pr("old_friend_calls",
      ["Yıllardır görmediğin eski bir arkadaşın aradı. Tepkin ne olur?",
        ["Çok sevinir, hemen görüşmek için plan yaparım", "Mutlu olurum ama biraz çekingen davranırım", "Önce ne istediğini düşünürüm", "Cevap vermeyi sonraya bırakırım"]],
      ["An old friend you haven't seen in years calls. How do you react?",
        ["Get excited and plan to meet right away", "Happy, but a little shy", "Wonder first what they want", "Put off answering"]],
      ["Te llama un viejo amigo al que llevas años sin ver. ¿Cómo reaccionas?",
        ["Me emociono y planeo vernos enseguida", "Me alegro, pero me muestro algo tímido", "Primero me pregunto qué querrá", "Dejo la respuesta para más tarde"]]),
    pr("taking_sides",
      ["Arkadaş grubunda biriyle aranız bozuldu ve diğerleri taraf tutmaya başladı. Ne yaparsın?",
        ["Tarafsız kalıp ikisiyle de konuşurum", "Haklı gördüğüm tarafı desteklerim", "Ortamdan çekilir, uzak dururum", "Herkesi bir araya getirip konuşturmayı denerim"]],
      ["You've fallen out with someone in your friend group and others start taking sides. What do you do?",
        ["Stay neutral and talk to both", "Support the side I think is right", "Withdraw and keep my distance", "Try to get everyone together to talk"]],
      ["Te has distanciado de alguien de tu grupo y los demás empiezan a tomar partido. ¿Qué haces?",
        ["Me mantengo neutral y hablo con ambos", "Apoyo al bando que creo que tiene razón", "Me aparto y me mantengo a distancia", "Intento reunir a todos para hablar"]]),
    pr("embarrassing_photo",
      ["Bir arkadaşın sosyal medyada seninle ilgili utanç verici eski bir fotoğraf paylaştı. Tepkin ne olur?",
        ["Gülüp ben de yorum yazarım", "Hemen silmesini rica ederim", "Önce kimlerin gördüğüne bakarım", "Karşılık olarak onun eski bir fotoğrafını paylaşırım"]],
      ["A friend posts an embarrassing old photo of you online. What's your reaction?",
        ["Laugh and comment too", "Ask them to take it down right away", "Check who's seen it first", "Retaliate by posting an old photo of them"]],
      ["Un amigo publica una foto antigua tuya que da vergüenza. ¿Cómo reaccionas?",
        ["Me río y comento yo también", "Le pido que la borre enseguida", "Primero miro quién la ha visto", "Respondo publicando una foto antigua suya"]]),
    pr("friend_moving_away",
      ["Bir arkadaşın yeni bir iş buldu ve başka bir şehre taşınıyor. Nasıl tepki verirsin?",
        ["Çok sevinirim, ziyarete gitme planları yaparım", "Üzülürüm ama belli etmem", "Düzenli arama sözü isterim", "Uzaklaşırsak bağın zayıflayacağından endişelenirim"]],
      ["A friend got a new job and is moving to another city. How do you react?",
        ["Be thrilled and plan visits", "Feel sad but not show it", "Ask them to promise regular calls", "Worry that we'll drift apart"]],
      ["Un amigo ha encontrado trabajo y se muda a otra ciudad. ¿Cómo reaccionas?",
        ["Me alegro y planeo visitas", "Me da pena pero no lo muestro", "Le pido que prometa llamadas regulares", "Me preocupa que nos distanciemos"]]),
    pr("game_night",
      ["Arkadaşlarla bir akşam toplandınız ve oynanacak oyun seçiliyor. Sen ne dersin?",
        ["Rekabetçi bir oyun seçelim", "Herkesin katılabileceği basit bir oyun olsun", "Oyunsuz, sohbet odaklı bir akşam olsun", "Ben izlerim, siz oynayın"]],
      ["At a friends' night in, the group is choosing a game. What do you say?",
        ["Let's pick a competitive game", "A simple game everyone can join", "A chat-focused evening, no games", "I'll watch, you play"]],
      ["En una noche de amigos, el grupo elige un juego. ¿Qué dices?",
        ["Elijamos un juego competitivo", "Un juego sencillo en el que pueda participar todo el mundo", "Una noche de charla, sin juegos", "Yo miro, vosotros jugad"]]),
    pr("cancelled_plans",
      ["Planlanan etkinliğe sadece sen ve bir arkadaşın gelebildi, diğerleri iptal etti. Ne yaparsın?",
        ["Aynen devam ederiz, iki kişi de eğlenir", "Başka bir tarihe erteleriz", "Diğerlerini ikna etmeye çalışırım", "İptal edip eve dönerim"]],
      ["Only you and one friend can make it to the planned event; the others cancel. What do you do?",
        ["Go ahead anyway, two is fun too", "Postpone to another date", "Try to convince the others", "Cancel and head home"]],
      ["Solo puedes ir tú y un amigo al plan; los demás cancelan. ¿Qué haces?",
        ["Seguimos adelante, entre dos también es divertido", "Lo aplazamos a otra fecha", "Intento convencer a los demás", "Cancelo y me voy a casa"]]),

    ol("friendship_values",
      ["Bir arkadaşlıkta en önemli şeyleri sırala:", ["Güven", "Birlikte eğlenmek", "Zor zamanda yanında olmak", "Dürüstlük"]],
      ["Rank what matters most in a friendship:", ["Trust", "Having fun together", "Being there in hard times", "Honesty"]],
      ["Ordena lo más importante en una amistad:", ["Confianza", "Divertirse juntos", "Estar en los momentos difíciles", "Honestidad"]]),
    ol("hangout_activities",
      ["Arkadaşlarınla yapmaktan en çok keyif aldığın şeyleri sırala:", ["Uzun sohbetler", "Oyun ya da yarışma", "Yeni yerler keşfetmek", "Birlikte yemek yemek"]],
      ["Rank what you enjoy most doing with friends:", ["Long conversations", "Games or competitions", "Exploring new places", "Eating together"]],
      ["Ordena lo que más disfrutas haciendo con amigos:", ["Conversaciones largas", "Juegos o competiciones", "Explorar sitios nuevos", "Comer juntos"]]),
    ol("group_irritants",
      ["Arkadaş ortamında en çok can sıkan şeyleri, en çok sıkandan başlayarak sırala:", ["Telefona gömülmek", "Hep aynı konuyu konuşmak", "Plan yapmamak, hep “bilmem” demek", "Birini sürekli dışlamak"]],
      ["Rank what annoys you most in a friend setting, starting with the biggest:", ["Being glued to the phone", "Always talking about the same thing", "Never making plans, always saying “dunno”", "Constantly leaving someone out"]],
      ["Ordena lo que más te molesta en un ambiente de amigos, empezando por lo peor:", ["Estar pegado al móvil", "Hablar siempre de lo mismo", "No proponer planes y decir siempre «no sé»", "Dejar a alguien de lado constantemente"]]),
    ol("gift_priorities",
      ["Bir arkadaşına hediye alırken neye önem verirsin? Sırala:", ["Kişiye özel olması", "Fiyatı", "Eğlenceli olması", "İşe yarar olması"]],
      ["When buying a friend a gift, what matters to you? Rank:", ["Being personal", "Price", "Being fun", "Being useful"]],
      ["Al regalar algo a un amigo, ¿qué te importa? Ordena:", ["Que sea personal", "El precio", "Que sea divertido", "Que sea útil"]]),
    ol("widening_circle",
      ["Arkadaş çevreni genişletmek için neler yaparsın? Sırala:", ["Etkinliklere katılmak", "Arkadaşlarımın arkadaşlarıyla tanışmak", "Online topluluklara katılmak", "Yeni hobiler edinmek"]],
      ["Rank how you'd widen your friend circle:", ["Joining events", "Meeting friends of friends", "Joining online communities", "Taking up new hobbies"]],
      ["Ordena cómo ampliarías tu círculo de amigos:", ["Asistir a eventos", "Conocer a amigos de amigos", "Unirme a comunidades online", "Empezar nuevas aficiones"]]),
    ol("friendship_strengtheners",
      ["Bir arkadaşlığı güçlendiren şeyleri sırala:", ["Düzenli görüşmek", "Zor zamanda yanında olmak", "Ortak anılar biriktirmek", "Birbirine dürüst olmak"]],
      ["Rank what strengthens a friendship:", ["Meeting regularly", "Being there in hard times", "Making shared memories", "Being honest with each other"]],
      ["Ordena lo que fortalece una amistad:", ["Verse con regularidad", "Estar en los momentos difíciles", "Crear recuerdos compartidos", "Ser sinceros el uno con el otro"]]),
    ol("gathering_roles",
      ["Bir arkadaş toplantısında en çok keyif aldığın rolleri sırala:", ["Ev sahibi olmak", "Hikâye anlatan olmak", "Dinleyen olmak", "Eğlenceyi organize eden olmak"]],
      ["Rank the roles you enjoy most at a friends' gathering:", ["Being the host", "Being the storyteller", "Being the listener", "Being the entertainment planner"]],
      ["Ordena los papeles que más disfrutas en una reunión de amigos:", ["Ser el anfitrión", "Ser el que cuenta historias", "Ser el que escucha", "Ser el que organiza la diversión"]]),
    ol("friend_criteria",
      ["Birini arkadaş olarak görmen için önem verdiğin şeyleri sırala:", ["Ortak mizah", "Benzer değerler", "Zor durumda destek olması", "Birlikte eğlenmek"]],
      ["Rank what matters for you to consider someone a friend:", ["Shared humor", "Similar values", "Support in hard times", "Having fun together"]],
      ["Ordena lo que importa para considerar amigo a alguien:", ["Humor compartido", "Valores similares", "Apoyo en los momentos difíciles", "Pasarlo bien juntos"]]),
    ol("birthday_gestures",
      ["Bir arkadaşının doğum günü için yapabileceğin jestleri sırala:", ["Sürpriz parti", "Kişiye özel bir hediye", "Uzun ve içten bir mesaj", "Birlikte güzel bir gün geçirmek"]],
      ["Rank the gestures you might do for a friend's birthday:", ["A surprise party", "A personalized gift", "A long, heartfelt message", "Spending a great day together"]],
      ["Ordena los detalles que harías por el cumpleaños de un amigo:", ["Una fiesta sorpresa", "Un regalo personalizado", "Un mensaje largo y sincero", "Pasar un gran día juntos"]]),
    ol("friend_routines",
      ["Arkadaşlarınla yaptığın şeyleri, en sık yaptığından başlayarak sırala:", ["Birlikte yemek yemek", "Telefonla konuşmak", "Spor yapmak", "Alışverişe çıkmak"]],
      ["Rank the things you do with friends, starting with the most frequent:", ["Eating together", "Talking on the phone", "Working out", "Going shopping"]],
      ["Ordena lo que haces con tus amigos, empezando por lo más frecuente:", ["Comer juntos", "Hablar por teléfono", "Hacer deporte", "Ir de compras"]]),
  ],
};
