import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Değerler — ortak (friend, dating, partner). Tür-bağımsız: ilişki/romantik çağrışım YOK.
export const values: SeedCategory = {
  slug: "values",
  names: { tr: "Değerler", en: "Values", es: "Valores" },
  relationshipTypes: ["friend", "dating", "partner"],
  isPremium: false,
  sortOrder: 10,
  questions: [
    sc("white_lies",
      "Birinin duygularını korumak için masum bir yalan söylemek sence kabul edilebilir mi?",
      "Do you think a harmless white lie to protect someone's feelings is acceptable?",
      "¿Crees que una mentira piadosa para proteger los sentimientos de alguien es aceptable?"),
    sc("keeping_promises",
      "Verdiğin sözü, işine gelmese bile tutmaya çalışır mısın?",
      "Do you try to keep your word even when it's inconvenient?",
      "¿Intentas cumplir tu palabra aunque no te convenga?"),
    sc("second_chance",
      "Seni hayal kırıklığına uğratan birine ikinci bir şans verir misin?",
      "Would you give a second chance to someone who let you down?",
      "¿Le darías una segunda oportunidad a alguien que te decepcionó?"),
    sc("ambition_vs_peace",
      "Başarı, senin için huzurdan daha öncelikli mi?",
      "Is success a higher priority for you than peace of mind?",
      "¿Es el éxito más prioritario para ti que la tranquilidad?"),
    sc("helping_strangers",
      "Tanımadığın birine, karşılığında bir şey beklemeden yardım eder misin?",
      "Would you help a stranger without expecting anything in return?",
      "¿Ayudarías a un desconocido sin esperar nada a cambio?"),
    sc("rules_following",
      "Bir kuralın mantıksız olduğunu düşünsen de yine de uyar mısın?",
      "If you think a rule is unreasonable, do you still follow it?",
      "Si crees que una norma no tiene sentido, ¿aun así la cumples?"),
    sc("tradition",
      "Aile ya da toplum geleneklerine uymak senin için önemli mi?",
      "Is following family or community traditions important to you?",
      "¿Es importante para ti seguir las tradiciones familiares o de tu comunidad?"),
    sc("own_convictions",
      "Önemli bir kararı, yakınların karşı çıksa bile kendi doğrularına göre verir misin?",
      "Would you make an important decision based on your own beliefs even if people close to you disagree?",
      "¿Tomarías una decisión importante según tus convicciones aunque tus seres queridos no estén de acuerdo?"),

    pr("moral_dilemma",
      ["Markette kasiyer yanlışlıkla sana fazla para üstü verdi ve fark ettin. Ne yaparsın?",
        ["Hemen geri veririm", "Çıkıştan sonra fark etsem bile geri dönerim", "Küçük bir miktarsa üstünde durmam", "Kasiyerin hatası, bana düşen bir şey değil"]],
      ["A cashier accidentally gives you too much change and you notice. What do you do?",
        ["Give it back right away", "Go back even if I notice after leaving", "Let it go if it's a small amount", "It's the cashier's mistake, not my problem"]],
      ["Un cajero te da cambio de más por error y te das cuenta. ¿Qué haces?",
        ["Lo devuelvo de inmediato", "Vuelvo aunque me dé cuenta al salir", "Lo dejo pasar si es poco", "Es error del cajero, no es mi problema"]]),
    pr("fear_of_losing",
      ["Hayatta en çok neyi kaybetmekten korkarsın?",
        ["Özgürlüğümü", "Sevdiklerimi", "Sağlığımı", "Huzurumu"]],
      ["What are you most afraid of losing in life?",
        ["My freedom", "The people I love", "My health", "My peace of mind"]],
      ["¿Qué es lo que más temes perder en la vida?",
        ["Mi libertad", "A mis seres queridos", "Mi salud", "Mi tranquilidad"]]),
    pr("risk_appetite",
      ["Sana güvenli ama sıradan bir iş ile riskli ama heyecan verici bir fırsat sunuldu. Seçimin ne olur?",
        ["Güvenli olanı seçerim", "Riskli olanı seçerim", "Önce riskleri uzun uzun araştırırım", "Başkalarının fikrine göre karar veririm"]],
      ["You're offered a safe but ordinary job or a risky but exciting opportunity. What do you choose?",
        ["The safe one", "The risky one", "Research the risks at length first", "Decide based on others' opinions"]],
      ["Te ofrecen un trabajo seguro pero normal o una oportunidad arriesgada pero emocionante. ¿Qué eliges?",
        ["La segura", "La arriesgada", "Investigo los riesgos a fondo primero", "Decido según la opinión de otros"]]),
    pr("fairness",
      ["Ekip çalışmasında biri hiç çalışmadı ama ödülü herkes aynı alacak. Ne yaparsın?",
        ["Açıkça konuşurum", "Sessizce katlanır, kendi işimi yaparım", "Sorumlu kişiye bildiririm", "Bir dahaki sefer o kişiyle çalışmam"]],
      ["In a team project someone did no work, but everyone will get the same reward. What do you do?",
        ["Speak up openly", "Quietly put up with it and do my part", "Tell whoever is in charge", "Avoid working with them next time"]],
      ["En un trabajo en equipo alguien no hizo nada, pero todos recibirán el mismo premio. ¿Qué haces?",
        ["Hablo abiertamente", "Lo aguanto en silencio y hago mi parte", "Se lo digo a quien esté al mando", "No vuelvo a trabajar con esa persona"]]),
    pr("helping_style",
      ["Bir hayır kampanyasına destek olmak istiyorsun. Nasıl yardım edersin?",
        ["Maddi bağış yaparım", "Gönüllü olarak zamanımı veririm", "Çevremde duyurup destek toplarım", "Sessizce, kimse bilmeden yaparım"]],
      ["You want to support a charity cause. How do you help?",
        ["Donate money", "Volunteer my time", "Spread the word and gather support", "Do it quietly, without anyone knowing"]],
      ["Quieres apoyar una causa solidaria. ¿Cómo ayudas?",
        ["Haciendo una donación", "Dando mi tiempo como voluntario", "Difundiéndolo y reuniendo apoyo", "En silencio, sin que nadie lo sepa"]]),

    ol("core_values",
      ["Hayatında en çok değer verdiğin şeyleri sırala:", ["Dürüstlük", "Özgürlük", "Güvenilirlik", "Başarı"]],
      ["Rank what you value most in life:", ["Honesty", "Freedom", "Reliability", "Achievement"]],
      ["Ordena lo que más valoras en la vida:", ["Honestidad", "Libertad", "Fiabilidad", "Éxito"]]),
    ol("decision_factors",
      ["Önemli bir karar verirken en çok neye güvenirsin? Sırala:", ["Mantık ve veriler", "İç sesim", "Yakınlarımın tavsiyesi", "Geçmiş deneyimlerim"]],
      ["When making an important decision, what do you trust most? Rank:", ["Logic and facts", "My gut feeling", "The advice of people close to me", "Past experience"]],
      ["Al tomar una decisión importante, ¿en qué confías más? Ordena:", ["La lógica y los datos", "Mi intuición", "El consejo de mis allegados", "La experiencia pasada"]]),
    ol("respected_traits",
      ["Birinde en çok saygı duyduğun özellikleri sırala:", ["Cesaret", "Mütevazılık", "Çalışkanlık", "Merhamet"]],
      ["Rank the traits you respect most in a person:", ["Courage", "Humility", "Hard work", "Compassion"]],
      ["Ordena los rasgos que más respetas en una persona:", ["Valentía", "Humildad", "Esfuerzo", "Compasión"]]),
    ol("intolerable_behaviors",
      ["Hangi davranışı hoş göremezsin? En affedilmez olandan başlayarak sırala:", ["Yalan söylemek", "Haksızlık yapmak", "Sorumluluktan kaçmak", "Saygısızlık"]],
      ["Which behavior can you not tolerate? Rank starting from the least forgivable:", ["Lying", "Being unfair", "Dodging responsibility", "Disrespect"]],
      ["¿Qué comportamiento no toleras? Ordena empezando por el menos perdonable:", ["Mentir", "Ser injusto", "Eludir responsabilidades", "La falta de respeto"]]),

    // ── Tamamlama: her modda 10'a ──────────────────────────────────────
    sc("stand_by_view",
      "Bir tartışmada karşı tarafı ikna edemesen bile görüşünü korur musun?",
      "In a debate, do you stand by your view even if you can't convince the other side?",
      "En un debate, ¿mantienes tu opinión aunque no consigas convencer a la otra parte?"),
    sc("environment",
      "Çevre için günlük hayatında bilinçli seçimler yapmaya çalışır mısın?",
      "Do you try to make conscious choices for the environment in daily life?",
      "¿Intentas tomar decisiones conscientes por el medio ambiente en tu día a día?"),

    pr("found_item",
      ["Yerde sana ait olmayan değerli bir eşya buldun. Ne yaparsın?",
        ["Sahibini bulmak için elimden geleni yaparım", "Yetkililere teslim ederim", "Sahibi çıkmazsa saklarım", "Görmemiş gibi geçerim"]],
      ["You find a valuable item on the ground that isn't yours. What do you do?",
        ["Do everything I can to find the owner", "Hand it to the authorities", "Keep it if no owner turns up", "Walk past as if I didn't see it"]],
      ["Encuentras un objeto valioso en el suelo que no es tuyo. ¿Qué haces?",
        ["Hago todo lo posible por encontrar al dueño", "Lo entrego a las autoridades", "Me lo quedo si nadie lo reclama", "Paso de largo como si no lo hubiera visto"]]),
    pr("rule_breaking_close",
      ["Yakınlarından biri küçük bir kuralı ihlal ediyor ve kimse görmedi. Ne yaparsın?",
        ["Kendisine nazikçe söylerim", "Görmezden gelirim", "Yetkili birine bildiririm", "Kuralın mantıklı olup olmadığına bakarım"]],
      ["Someone close to you breaks a small rule and nobody notices. What do you do?",
        ["Gently tell them", "Ignore it", "Report it to someone in charge", "Consider whether the rule even makes sense"]],
      ["Alguien cercano incumple una norma menor y nadie lo ve. ¿Qué haces?",
        ["Se lo digo con tacto", "Lo ignoro", "Se lo comunico a alguien con autoridad", "Valoro si la norma tiene sentido"]]),
    pr("unlimited_time",
      ["Bir gün sınırsız zamanın olsa en çok neye ayırırdın?",
        ["Öğrenmeye ve gelişmeye", "Sevdiklerimle vakit geçirmeye", "Başkalarına yardım etmeye", "Keşfetmeye ve gezmeye"]],
      ["If you had unlimited time one day, what would you devote it to?",
        ["Learning and growing", "Time with loved ones", "Helping others", "Exploring and traveling"]],
      ["Si un día tuvieras tiempo ilimitado, ¿a qué lo dedicarías?",
        ["A aprender y crecer", "A estar con mis seres queridos", "A ayudar a otros", "A explorar y viajar"]]),
    pr("handling_failure",
      ["Başarısız olduğun bir işin ardından ne yaparsın?",
        ["Nedenini analiz edip yeniden denerim", "Bir süre moralim bozulur, sonra toparlanırım", "Başka bir alana yönelirim", "Destek alıp konuşurum"]],
      ["After failing at something, what do you do?",
        ["Analyze why and try again", "Feel down for a while, then recover", "Move to a different area", "Seek support and talk it through"]],
      ["Tras fracasar en algo, ¿qué haces?",
        ["Analizo por qué y vuelvo a intentarlo", "Me hundo un tiempo y luego me recupero", "Me oriento a otro ámbito", "Busco apoyo y lo hablo"]]),
    pr("asking_for_help",
      ["Yardıma ihtiyacın olduğunda nasıl davranırsın?",
        ["Hemen yardım isterim", "Önce kendim çözmeye çalışırım", "Çok zorlanmadıkça istemem", "Kimseye yük olmak istemem"]],
      ["When you need help, how do you behave?",
        ["Ask for it right away", "Try to solve it myself first", "Don't ask unless I'm really struggling", "I don't want to be a burden to anyone"]],
      ["Cuando necesitas ayuda, ¿cómo te comportas?",
        ["La pido enseguida", "Primero intento resolverlo yo", "No la pido a menos que me cueste mucho", "No quiero ser una carga para nadie"]]),

    ol("society_priorities",
      ["Bir toplumun en çok önem vermesi gereken şeyleri sırala:", ["Eğitim", "Sağlık", "Adalet", "Çevre"]],
      ["Rank what a society should prioritize most:", ["Education", "Health", "Justice", "The environment"]],
      ["Ordena lo que una sociedad debería priorizar más:", ["Educación", "Salud", "Justicia", "Medio ambiente"]]),
    ol("impressive_traits",
      ["Bir insanda seni en çok etkileyen özellikleri sırala:", ["Kararlılık", "Nezaket", "Zeka", "Özgünlük"]],
      ["Rank the traits that impress you most in a person:", ["Determination", "Kindness", "Intelligence", "Originality"]],
      ["Ordena los rasgos que más te impresionan en una persona:", ["Determinación", "Amabilidad", "Inteligencia", "Originalidad"]]),
    ol("quality_of_life",
      ["Yaşam kalitesini en çok artıran şeyleri sırala:", ["Sağlık", "Özgürlük", "Güvenli bir gelecek", "Anlamlı bir iş"]],
      ["Rank what improves quality of life the most:", ["Health", "Freedom", "A secure future", "Meaningful work"]],
      ["Ordena lo que más mejora la calidad de vida:", ["Salud", "Libertad", "Un futuro seguro", "Un trabajo con sentido"]]),
    ol("after_mistake",
      ["Bir hatadan sonra yapılması gerekenleri öncelik sırasına göre sırala:", ["Sorumluluğu üstlenmek", "Özür dilemek", "Düzeltmek için harekete geçmek", "Ders çıkarmak"]],
      ["Rank what should happen after a mistake, in order of priority:", ["Taking responsibility", "Apologizing", "Acting to fix it", "Learning the lesson"]],
      ["Ordena lo que debería ocurrir tras un error, por orden de prioridad:", ["Asumir la responsabilidad", "Disculparse", "Actuar para repararlo", "Aprender la lección"]]),
    ol("valuable_achievement",
      ["Bir başarıyı değerli yapan şeyleri sırala:", ["Emek verilmiş olması", "Dürüstçe kazanılması", "Başkalarına faydası", "Beklenmedik olması"]],
      ["Rank what makes an achievement valuable:", ["Effort put in", "Being earned honestly", "Benefiting others", "Being unexpected"]],
      ["Ordena lo que hace valioso un logro:", ["El esfuerzo invertido", "Haberlo conseguido con honestidad", "El beneficio para otros", "Que sea inesperado"]]),
    ol("decision_principles",
      ["Bir kararda en çok önemsemen gereken ilkeleri sırala:", ["Adalet", "Merhamet", "Pratiklik", "Uzun vadeli fayda"]],
      ["Rank the principles that matter most in a decision:", ["Fairness", "Compassion", "Practicality", "Long-term benefit"]],
      ["Ordena los principios que más importan en una decisión:", ["Justicia", "Compasión", "Practicidad", "Beneficio a largo plazo"]]),
  ],
};
