import type { SeedCategory } from "./types.ts";
import { sc, pr, ol } from "./helpers.ts";

// Çılgın Senaryolar — yalnızca "friend". Eğlenceli, hayalî durumlar; romantik çağrışım YOK (denetlenir).
export const wildScenarios: SeedCategory = {
  slug: "wild_scenarios",
  names: { tr: "Çılgın Senaryolar", en: "Wild Scenarios", es: "Escenarios locos" },
  relationshipTypes: ["friend"],
  isPremium: false,
  sortOrder: 2,
  questions: [
    sc("zombie_leader",
      "Zombi istilasında grubun lideri olmak ister misin?",
      "In a zombie apocalypse, would you want to be the group's leader?",
      "En un apocalipsis zombi, ¿querrías ser el líder del grupo?"),
    sc("desert_island",
      "Issız bir adada bir hafta tek başına hayatta kalabileceğine inanır mısın?",
      "Do you believe you could survive alone on a deserted island for a week?",
      "¿Crees que podrías sobrevivir una semana solo en una isla desierta?"),
    sc("future_vs_past",
      "Zaman makinen olsa, geçmişe dönmek yerine geleceğe gitmeyi seçer misin?",
      "If you had a time machine, would you pick the future over the past?",
      "Si tuvieras una máquina del tiempo, ¿preferirías el futuro al pasado?"),
    sc("lottery_secret",
      "Büyük ikramiyeyi kazansan, bunu yalnızca birkaç yakınına söyler misin?",
      "If you won the lottery, would you tell only a few people close to you?",
      "Si te tocara la lotería, ¿se lo dirías solo a unas pocas personas cercanas?"),
    sc("fame",
      "Bir gün ünlü olsan, bunu keyifle karşılar mısın?",
      "If you suddenly became famous, would you enjoy it?",
      "Si de repente te hicieras famoso, ¿lo disfrutarías?"),
    sc("harmless_prank",
      "Arkadaşlarına masum bir şaka yapıp onları şaşırtmaktan keyif alır mısın?",
      "Do you enjoy pulling a harmless prank on friends to surprise them?",
      "¿Disfrutas gastando una broma inofensiva a tus amigos para sorprenderlos?"),
    sc("skydiving",
      "Paraşütle atlama fırsatı sunulsa, tereddüt etmeden kabul eder misin?",
      "If offered the chance to skydive, would you accept without hesitating?",
      "Si te ofrecieran saltar en paracaídas, ¿aceptarías sin dudar?"),
    sc("invisibility_fun",
      "Bir günlüğüne görünmez olsan, bunu eğlenceli şeyler için kullanır mısın?",
      "If you were invisible for a day, would you use it for fun things?",
      "Si fueras invisible un día, ¿lo usarías para divertirte?"),
    sc("solo_exploration",
      "Hiç tanımadığın bir şehirde bir gün tek başına dolaşmak seni heyecanlandırır mı?",
      "Does wandering alone through a city you don't know sound exciting?",
      "¿Te emociona la idea de pasear solo por una ciudad que no conoces?"),
    sc("mind_reading",
      "Bir günlüğüne başkalarının aklını okuyabilsen bunu denemek ister misin?",
      "If you could read people's minds for a day, would you want to try?",
      "Si pudieras leer la mente de los demás durante un día, ¿querrías probarlo?"),

    pr("superpower",
      ["Bir süper güç seçme hakkın olsa hangisini seçersin?",
        ["Zihin okumak", "Uçmak", "Zamanı durdurmak", "Görünmez olmak"]],
      ["If you could pick a superpower, which would you choose?",
        ["Reading minds", "Flying", "Stopping time", "Invisibility"]],
      ["Si pudieras elegir un superpoder, ¿cuál elegirías?",
        ["Leer mentes", "Volar", "Detener el tiempo", "Ser invisible"]]),
    pr("zombie_role",
      ["Zombi istilasında grubunda hangi rolü üstlenirsin?",
        ["Lider: planı ben yaparım", "Yiyecek ve kaynak bulan", "Moral veren, şakacı", "Gizlice ayrılıp kendi yoluma giderim"]],
      ["In a zombie apocalypse, what role do you take in your group?",
        ["Leader: I make the plan", "Finder of food and supplies", "The morale booster, the joker", "Quietly slip away and go my own way"]],
      ["En un apocalipsis zombi, ¿qué papel asumes en tu grupo?",
        ["Líder: yo hago el plan", "El que busca comida y recursos", "El que anima y hace reír", "Me escabullo y sigo mi propio camino"]]),
    pr("stuck_elevator",
      ["Arkadaşlarınla asansörde mahsur kaldın. Ne yaparsın?",
        ["Sakin kalıp herkesi sakinleştiririm", "Acil durum butonuna basıp yardım ararım", "Espri yaparak ortamı yumuşatırım", "İçten içe panik olurum ama belli etmem"]],
      ["You're stuck in an elevator with your friends. What do you do?",
        ["Stay calm and calm everyone down", "Press the emergency button and call for help", "Crack jokes to lighten the mood", "Panic inside but don't show it"]],
      ["Os quedáis atrapados en un ascensor con tus amigos. ¿Qué haces?",
        ["Mantengo la calma y tranquilizo a todos", "Pulso el botón de emergencia y pido ayuda", "Hago bromas para aligerar el ambiente", "Entro en pánico por dentro, pero no lo muestro"]]),
    pr("invisible_day",
      ["Bir günlüğüne görünmez olsaydın ilk ne yapardın?",
        ["Arkadaşlarıma şaka yapardım", "Merak ettiğim yerlere girerdim", "İnsanların kimse bakmazken nasıl davrandığını izlerdim", "Hiçbir şey yapmaz, sadece huzurun tadını çıkarırdım"]],
      ["If you were invisible for a day, what would you do first?",
        ["Prank my friends", "Sneak into places I'm curious about", "Watch how people act when no one's looking", "Nothing, just enjoy the peace"]],
      ["Si fueras invisible un día, ¿qué harías primero?",
        ["Gastar bromas a mis amigos", "Colarme en sitios que me dan curiosidad", "Observar cómo se comporta la gente cuando nadie mira", "Nada, solo disfrutar de la tranquilidad"]]),
    pr("alien_contact",
      ["Uzaylılar dünyaya iniyor ve ilk senin yanına geliyorlar. Tepkin ne olur?",
        ["Merak edip konuşmaya çalışırım", "Telefonu çıkarıp video çekerim", "Kaçıp saklanırım", "Sakince “Hoş geldiniz” derim"]],
      ["Aliens land and walk up to you first. What's your reaction?",
        ["Get curious and try to talk to them", "Whip out my phone and film it", "Run and hide", "Calmly say “Welcome”"]],
      ["Aterrizan alienígenas y se acercan a ti primero. ¿Cómo reaccionas?",
        ["Me da curiosidad e intento hablar con ellos", "Saco el móvil y lo grabo", "Salgo corriendo y me escondo", "Digo con calma «Bienvenidos»"]]),
    pr("sudden_fame",
      ["Bir sabah uyandın ve herkes seni ünlü biri olarak tanıyor. İlk ne yaparsın?",
        ["Bunun tadını çıkarırım", "Sakin bir yer bulup saklanırım", "Nedenini araştırırım", "Bu şöhretle bir şeyler başarmaya çalışırım"]],
      ["You wake up one day and everyone knows you as a celebrity. What do you do first?",
        ["Enjoy it", "Find a quiet place to hide", "Investigate why", "Use the fame to achieve something"]],
      ["Un día te despiertas y todo el mundo te conoce como famoso. ¿Qué haces primero?",
        ["Lo disfruto", "Busco un sitio tranquilo para esconderme", "Investigo por qué", "Aprovecho para lograr algo"]]),
    pr("dream_destination",
      ["Sana 24 saat boyunca dilediğin yere gitme hakkı verildi. Nereye gidersin?",
        ["Hiç gitmediğim uzak bir ülkeye", "Çocukluğumun geçtiği yere", "Tarihin önemli bir anına", "Hiçbir yere, evimde dinlenirim"]],
      ["You get 24 hours to go anywhere you like. Where do you go?",
        ["A far-off country I've never been to", "Where I spent my childhood", "An important moment in history", "Nowhere, I rest at home"]],
      ["Tienes 24 horas para ir donde quieras. ¿Adónde vas?",
        ["A un país lejano que nunca he visitado", "Al lugar de mi infancia", "A un momento importante de la historia", "A ninguna parte, descanso en casa"]]),
    pr("talking_animals",
      ["Hayvanlarla konuşabilme yeteneği kazandın. Hangisiyle konuşmak istersin?",
        ["Bir evcil hayvanla", "Bir kartalla, bakış açısını duymak için", "Bir deniz canlısıyla", "Hiçbiriyle, sessizlik güzel"]],
      ["You gain the ability to talk to animals. Which would you talk to?",
        ["A pet", "An eagle, to hear its perspective", "A sea creature", "None, silence is nice"]],
      ["Ganas la capacidad de hablar con animales. ¿Con cuál hablarías?",
        ["Con una mascota", "Con un águila, para oír su perspectiva", "Con una criatura marina", "Con ninguno, el silencio es agradable"]]),
    pr("treasure_hunt",
      ["Dünyanın en büyük hazine avına katıldın. Takımdaki rolün ne olur?",
        ["Haritayı okuyan ve yol gösteren", "Cesur kâşif, ilk giren", "Malzeme ve yiyecek sorumlusu", "Takımı motive eden, moral veren"]],
      ["You join the world's biggest treasure hunt. What's your role on the team?",
        ["The map reader and guide", "The brave explorer who goes in first", "The supplies and food manager", "The motivator who keeps morale up"]],
      ["Participas en la mayor búsqueda del tesoro del mundo. ¿Cuál es tu papel en el equipo?",
        ["El que lee el mapa y guía", "El explorador valiente que entra primero", "El responsable de suministros y comida", "El que motiva y mantiene la moral"]]),
    pr("dream_job_day",
      ["Bir gün boyunca istediğin mesleği yapma hakkın var. Hangisini seçersin?",
        ["Astronot", "Dünyaca ünlü şef", "Film yönetmeni", "Dedektif"]],
      ["You get to do any job you like for a day. Which do you pick?",
        ["Astronaut", "World-famous chef", "Film director", "Detective"]],
      ["Puedes ejercer el trabajo que quieras durante un día. ¿Cuál eliges?",
        ["Astronauta", "Chef de fama mundial", "Director de cine", "Detective"]]),

    ol("survival_priorities",
      ["Issız bir adada hayatta kalmak için önceliklerini sırala:", ["Su bulmak", "Barınak yapmak", "Ateş yakmak", "Yardım çağırmak"]],
      ["Rank your priorities for surviving on a deserted island:", ["Finding water", "Building shelter", "Making fire", "Signaling for help"]],
      ["Ordena tus prioridades para sobrevivir en una isla desierta:", ["Encontrar agua", "Construir un refugio", "Hacer fuego", "Pedir ayuda"]]),
    ol("space_trip_items",
      ["Uzay yolculuğuna yanına alacağın şeyleri öncelik sırasına göre sırala:", ["Müzik listesi", "Kitaplar ya da oyunlar", "Favori yiyeceklerin", "Bir arkadaşının fotoğrafı"]],
      ["Rank what you'd take on a space trip, in order of priority:", ["A playlist", "Books or games", "Favorite snacks", "A photo of a friend"]],
      ["Ordena lo que llevarías a un viaje espacial, por orden de prioridad:", ["Una playlist", "Libros o juegos", "Tus snacks favoritos", "Una foto de un amigo"]]),
    ol("superhero_abilities",
      ["Süper kahraman olsan hangi yeteneğe en çok sahip olmak isterdin? Sırala:", ["Işık hızında koşmak", "Uçmak", "Çok güçlü olmak", "Zihin okumak"]],
      ["If you were a superhero, which ability would you most want? Rank:", ["Super speed", "Flight", "Super strength", "Mind reading"]],
      ["Si fueras un superhéroe, ¿qué habilidad querrías más? Ordena:", ["Supervelocidad", "Volar", "Superfuerza", "Leer mentes"]]),
    ol("unusual_experiences",
      ["Hayatında denemek isteyeceğin sıra dışı deneyimleri, en çok istediğinden başlayarak sırala:", ["Balonla uçmak", "Okyanus dibinde dalmak", "Bir film setinde figüran olmak", "Bir günlüğüne ünlü bir şef olmak"]],
      ["Rank the unusual experiences you'd most like to try, starting with your top pick:", ["A hot air balloon ride", "Diving deep in the ocean", "Being an extra on a movie set", "Being a famous chef for a day"]],
      ["Ordena las experiencias poco comunes que más te gustaría probar, empezando por tu favorita:", ["Un paseo en globo", "Bucear en las profundidades del océano", "Ser figurante en un rodaje", "Ser un chef famoso por un día"]]),
    ol("adventure_companion",
      ["Çılgın bir maceraya çıkarken yanında olmasını istediğin kişinin özelliklerini sırala:", ["Cesur olması", "Mizah anlayışı", "Sakin kalabilmesi", "Yaratıcı fikirleri"]],
      ["Rank the traits you'd want in a companion on a crazy adventure:", ["Courage", "A sense of humor", "Staying calm", "Creative ideas"]],
      ["Ordena los rasgos que querrías en un compañero para una aventura loca:", ["Valentía", "Sentido del humor", "Mantener la calma", "Ideas creativas"]]),
    ol("space_station_misses",
      ["Bir uzay istasyonunda yaşasan en çok özleyeceğin şeyleri sırala:", ["Doğa ve yeşillik", "Arkadaşlar", "Yemekler", "Özgürce yürüyebilmek"]],
      ["If you lived on a space station, rank what you'd miss most:", ["Nature and greenery", "Friends", "Food", "Walking freely"]],
      ["Si vivieras en una estación espacial, ordena lo que más echarías de menos:", ["La naturaleza y el verde", "A los amigos", "La comida", "Poder caminar libremente"]]),
    ol("prize_choice",
      ["Tuhaf bir yarışmayı kazansan hangi ödülleri seçerdin? Sırala:", ["Dünya turu", "Bir yıllık bedava yemek", "Hayalindeki bir teknoloji ürünü", "Ünlü biriyle bir gün"]],
      ["If you won a strange contest, rank the prizes you'd choose:", ["A trip around the world", "A year of free food", "A dream gadget", "A day with a celebrity"]],
      ["Si ganaras un concurso extraño, ordena los premios que elegirías:", ["Un viaje alrededor del mundo", "Un año de comida gratis", "Un aparato de ensueño", "Un día con un famoso"]]),
    ol("time_travel_eras",
      ["Zaman yolculuğunda gitmek isteyeceğin dönemleri sırala:", ["Dinozorlar çağı", "Antik Mısır", "Yakın gelecek", "Çocukluğum"]],
      ["Rank the eras you'd want to visit by time travel:", ["The age of dinosaurs", "Ancient Egypt", "The near future", "My childhood"]],
      ["Ordena las épocas a las que querrías viajar en el tiempo:", ["La era de los dinosaurios", "El Antiguo Egipto", "El futuro cercano", "Mi infancia"]]),
    ol("forest_survival",
      ["Bir ormanda kaybolsan sana en çok lazım olacak şeyleri sırala:", ["Pusula", "Bıçak", "Su arıtma tableti", "Çakmak"]],
      ["If you were lost in a forest, rank what you'd need most:", ["A compass", "A knife", "Water purification tablets", "A lighter"]],
      ["Si te perdieras en un bosque, ordena lo que más necesitarías:", ["Una brújula", "Un cuchillo", "Pastillas potabilizadoras", "Un mechero"]]),
    ol("movie_genre",
      ["Bir film karakteri olsan hangi türde olmayı seçerdin? Sırala:", ["Macera", "Komedi", "Bilim kurgu", "Gizem"]],
      ["If you were a movie character, rank the genres you'd choose:", ["Adventure", "Comedy", "Sci-fi", "Mystery"]],
      ["Si fueras un personaje de película, ordena los géneros que elegirías:", ["Aventura", "Comedia", "Ciencia ficción", "Misterio"]]),
  ],
};
